PayButton/paybutton-server

server/utils/bchd.ts
=> fix(bchd): adds proper greyhat url

.docker/Dockerfile, Makefile, README.md, package-lock.json, package.json
To make it easier to develop in a consistent way across different machines/OS, this patch adds a dockerfile and a makefile to build a local image, caching installed dependencies and running the container.
=> chore: add dockerfile and a makefile to run local server

config/backendConfig.ts, config/frontendConfig.tsx, next.config.js
Adds GitHub third party provider, enabling users to sign in/sign up with their Github accounts.
=> feat: add Github auth option

config/backendConfig.ts, config/frontendConfig.tsx, next.config.js
Adds option for users to login with google.
WARNING: uses supertokens.io google credentials. Reminder to set up own app credentials.
=> feat: add google auth option

config/backendConfig.ts, next.config.js
Description: adds supertokens api key and uri to environment variables
Test Plan: make sure website is working, including social logins.
=> chore: add supertokens api key and uri env vars

.github/workflows/deployment-check.yml
Description: adds a second round of find and replace since the action replaces only occurences
Test Plan: check for PR comments on branches with more than one slash, see if URL is correct
=> ci: fix deployment check to replace all occurences of slashes

pages/index.tsx
Description: adds "Create Button" button on signed-in page
Test Plan: open feat-add-button-1.paybutton.io and check if "Add Button" button is displayed
=> feat: Add PayButton [Part 1]

components/AddPayButtonForm.tsx, package.json, pages/index.tsx, yarn.lock
Description: adds a basic pay button form and required dependencies,
like material UI and data-driven-form
Test Plan: go to feat-add-button-2.paybutton.io and check in the signed in page
for the temporary form
Depends on: feat/add-button/1
=> feat: Add PayButton [Part 2] 

components/AddPayButtonForm.tsx, components/PayButton/PayButtonsList.tsx, pages/api/paybutton/index.ts, pages/index.tsx, types/index.ts
Description: Removes 'mocked-user-id' from API, using userId provided by the app
Test Plan: `make dev`, go to http://localhost:3000 and then submit a form, a list with payButtonId and addresses associated with it should appear after submiting.
=> fix: remove mocked user id from api

README.md
Description: Fix README.md formatting, remove netlify badge and remove detailed instructions on social providers as (1) it's redundant since the provided link has a more detailed explanation already and (2) social login might not work properly on localhost depending on the social provider, so it could be misleading to newcomers.
Test Plan: [Check README preview here](https://github.com/PayButton/paybutton-server/tree/docs/update-readme#readme)
=> docs: update README and fix formatting

config/backendConfig.ts, config/frontendConfig.tsx
Description: Refactor backend and frontend config files inside config/, following **ts-standard** conventions.
Test Plan: `make dev`, check if everything is running. `npx ts-standard config/backendConfig`, `npx ts-standard config/frontendConfig` should both pass.
=> refactor: fix ts-standard on config files at config

config/appInfo.ts
Description: update appInfo.ts, making it follow our new ts-standard format.
Test Plan:  `npx ts-standard config/appInfo.ts` should not fail.
=> refactor: update appInfo.ts following ts-standard

.github/workflows/pull-request-linter-formatter.yml, Makefile, package.json
Description: Adds `ts-standard` linter and formatter for every PR. 
Test Plan: For this PR, check if the newly added actions run by either going to Actions menu item above or seeing one more check in the PR.
Depends on #69.
=> ci: add lint and format check for every PR

pages/api/user.ts
Description: Fix lint/ts-standard issues on user.ts
Test Plan: `npx ts-standard pages/api/user.ts` should show no linting errors.
=> chore: fix lint for user.ts

pages/api/transaction/[transactionId].ts, tests/integration-tests/api.test.ts
Description: fix/refactor transaction API and fix tests. 
Test Plan: lint and tests should pass, should work the same as #111.
=> fix: refactor transaction api and fix tests

components/Paybutton/PaybuttonList.tsx, services/paybuttonsService.ts, tests/integration-tests/api.test.ts
Description:
Solves #142, saves addresses in the DB with the prefix.
Test plan:
Nothing special, tests already cover this.
=> Chore: Save address with prefix

components/Layout/layout.module.css, components/Sidebar/index.tsx, components/Sidebar/sidebar.module.css, pages/dashboard/dashboard.module.css, styles/global.css
adding a mobile menu slide out for smaller screensizes
=> [Issue #166} UI Feature: Add mobile menu 

prisma/seed.ts, prisma/seeds/paybuttons.ts
Description:
Creates some PayButtons automatically, to simplify developing & testing.
Test Plan:
Recreate the containers with `make reset-dev` or simply reset the migrations with `yarn docker mr` and check if the following buttons were created for the default dev user.
=> [Issue #191] feat: seed mock paybuttons

constants/index.ts, prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, prisma/seed.ts, prisma/seeds/networks.ts, prisma/seeds/paybuttons.ts, services/addressesService.ts, services/networksService.ts, services/paybuttonsService.ts, tests/mockedObjects.ts, tests/unittests/paybuttonsService.test.ts, tests/unittests/validators.test.ts, types/index.ts
Description:
Solves #153. I ran commands to make the following substitution accross the code:
`chain` -> `network`
`Chain` -> `Network`
`CHAIN` -> `NETWORK`
Test Plan:
=> [Issue #153] refactor: rename chain to network

components/Network/NetworkList.tsx, components/Network/index.tsx, config/appInfo.ts, pages/api/networks/index.ts, pages/networks/index.tsx, services/networksService.ts
Description:
Shows the available networks on http://localhost:3000/networks
Test plan:
http://localhost:3000/networks should display:
=> [Issue #155] feat: Display networks

components/Network/NetworkList.tsx, components/Network/network.module.css, components/Sidebar/index.tsx, pages/networks/index.tsx
Style updates for the network page
=> [Issue #155] feat: network page styles

pages/api/dashboard/index.ts
Description:
Fixes  #224.
Test plan:
Check #224.
=> [Issue #224] fix: filter by `networkId` instead of `id`

components/Layout/layout.module.css, components/Paybutton/PaybuttonForm.tsx, components/Paybutton/paybutton.module.css, components/Sidebar/index.tsx, components/Sidebar/sidebar.module.css, pages/buttons/index.tsx
A few ui updates
- Change sidebar breakpoint to 960px
- Link nav logo to dashboard
- Update create button form to display specific errors, clear itself after submitting or canceling, multi/single address toggle, and submit with enter key
=> [Issue #225] feat:ui improvements

prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, prisma/seed.ts, prisma/seeds/addresses.ts, prisma/seeds/connectors.ts, prisma/seeds/paybuttons.ts, prisma/seeds/wallets.ts, tests/mockedObjects.ts
Description:
Create the `Wallet` model, migrations and the wallet objects to seed.
Test Plan:
Run `make reset-dev`
Enter the database with `yarn docker db`
See if the wallet table exists and is not empty: `SELECT * FROM Wallet;`
=> [Issue #154] feat: wallets scheme, migrations & seed

services/paybuttonService.ts, tests/integration-tests/api.test.ts, tests/mockedObjects.ts
Description:
Some changes related to typing the `Paybutton` objects returned by functions in `services/paybuttonService.ts`. The format of the returned object was fixed in the `tests/mockedObjects.ts` file.
Test Plan:
=> [Issue #154] chore: fix paybutton service typing and tests

prisma/seeds/addresses.ts, prisma/seeds/connectors.ts, prisma/seeds/paybuttons.ts, prisma/seeds/wallets.ts
Description:
Adds two new paybuttons, each one with a new address, and then two wallets, one for each paybutton. This will help for better testing the implementation of the `Wallet` model across the code.
Test plan:
=> Chore/ add more objects to seed

components/Transaction/TransactionDetail.tsx, pages/dashboard/Chart.tsx, pages/dashboard/index.tsx, utils/copyText.js, utils/general.js, utils/general.ts
Fixes for issue #247 
- Have minimum Y-axis value always be 0
- Add '$' prefix to tooltips
- Format (add commas) to chart values and header 
will address the new "all" button in another PR
=> [Issue #247] improvements:dashboard

components/Wallet/EditWalletForm.tsx, components/Wallet/WalletCard.tsx, components/Wallet/wallet.module.css, pages/api/wallets/index.ts, pages/wallets/index.tsx, tests/integration-tests/api.test.ts
Description:
Implements a functional front end for editing wallets. No backend implementation yet.
Test Plan:
Go to http://localhost:3000/wallets and click on the pencil icon to edit the wallet. The form should show the correct information when submited, on the console, as in the picture below:
Depends on:
=> [Issue #154] feat: Wallet edit front end

components/Wallet/EditWalletForm.tsx
Description:
Refactor some parameters name on `components/Wallet/EditWalletForm.tsx`
Test plan:
Depends on:
=> [Issue #154] feat: refactor wallet edit front end

components/Wallet/EditWalletForm.tsx
Description:
I had accidentally set the base branch of #281 as `feat/multiple-default-wallet` instead of `master`, so when it was merged, it wasn't merged to master, but to this other branch.
This is the same as #281 but with `master` as the base branch.
=> #281 redo 

components/Wallet/EditWalletForm.tsx, config/appInfo.ts, pages/api/wallet/[id].ts, services/walletService.ts, tests/integration-tests/api.test.ts, tests/mockedObjects.ts, tests/unittests/walletService.test.ts
Description:
Editing a wallet's name also works now.
Test plan:
Go to http://localhost:3000/wallets and try to change the wallets' names. 
Depends on:
=> [#154 Issue] feat: wallet edit back end name

prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, prisma/seed.ts, prisma/seeds/prices.ts, prisma/seeds/quotes.ts, services/transactionService.ts
Description:
Create one table for prices, another one for their quotes (BTC and USD for now) and another one connecting prices to transactions.
Test plan:
Nothing yet, only the models are being created.
=> [Issue #223] feat: create prices tables

.env, .env.test, config/appInfo.ts, config/backendConfig.ts, constants/index.ts, prisma/schema.prisma, services/priceService.ts, services/transactionService.ts, tests/mockedObjects.ts, tests/unittests/addressService.test.ts, tests/unittests/priceService.test.ts
Description:
Creates the price services & syncs prices together with transactions.
Test plan:
1. Delete the transactions from the database:
```
$ yarn docker db
...
> DELETE FROM Transaction;
```
2. Log out and back in to resync them with the prices
3. Check if the tables have been populated
```
...
> SELECT * FROM Price;
> SELECT * FROM PricesOnTransactions;
``` 
Depends on:
=> [Issue #223] feat: price services

Makefile, config/appInfo.ts, constants/index.ts, services/priceService.ts, services/transactionService.ts, tests/unittests/priceService.test.ts
Description:
Some minor changes needed for the use of real prices in the dashboard.
Test plan:
N/A
=> [Issue #151] feat: dependencies to using real prices on the dashboard

pages/api/paybutton/[id].ts, prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, services/paybuttonService.ts, tests/integration-tests/api.test.ts, tests/unittests/paybuttonService.test.ts, utils/validators.ts
Description:
Back end logic for deleting paybuttons.
Test plan:
Should be covered by the tests.
=>  [Issue #245] feat: backend for deleting paybuttons

components/Network/NetworkList.tsx, services/networkService.ts
Description:
Solves #310 using Scott's suggested function.
Test plan:
Go to http://localhost:3000/networks and check if the 'time since' is being nicely displayed.
=> [Issue #310] feat: using moment.fromNow to show time since last block

components/Paybutton/EditButtonForm.tsx, components/Paybutton/PaybuttonDetail.tsx, components/Paybutton/PaybuttonList.tsx, pages/api/paybutton/[id].ts, pages/button/[id].tsx, pages/buttons/index.tsx, prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, services/paybuttonService.ts, tests/integration-tests/api.test.ts, tests/unittests/paybuttonService.test.ts, utils/validators.ts
Description:
Solves #245. Users can delete paybuttons from the frontend, on the button detail page.
Test plan:
Go to http://localhost:3000/buttons, select any button and try to delete it by clicking on the pencil. Note that the "Edit" function is not implemented yet, only the "Delete".
Depends on:
=> [Issue #245] feat: delete paybutton

constants/index.ts, services/addressService.ts, services/networkService.ts, services/paybuttonService.ts, services/priceService.ts
Description:
Dependencies for the implementation of #324. Some refactors and the creation of constants.
Test plan:
=> [Issue #324] feat: dependencies for current price endpoint

constants/index.ts, pages/api/price/[networkSlug].ts, pages/api/price/[networkSlug]/[quoteSlug].ts, services/addressService.ts, services/networkService.ts, services/paybuttonService.ts, services/priceService.ts, tests/integration-tests/api.test.ts, tests/unittests/priceService.test.ts, tests/utils.ts
Creates an API endpoint to get current prices from the DB.
**Test plan:**
Tests should be covering. Experiment with requests such as:
```
curl http://localhost:3000/price/bitcoincash
```
should return `bitcoincash`'s current price in USD,
```
curl http://localhost:3000/price/ecash/cad
```
should return `ecash`'s current price in CAD
----
Depends on:
=>  [Issue #324] feat: current price endpoint

services/addressService.ts, services/grpcService.ts, services/transactionService.ts, utils/index.ts
Description:
Some refactors / services added for the next PRs implementing the automatic syncing of new transactions.
Test plan:
N/A
=> [Issue #322] feat: sync txs subscription dependencies

.gitignore, constants/index.ts, jobs/initJobs.ts, jobs/workers.ts, scripts/docker-exec-shortcuts.sh, scripts/paybutton-server-start.sh
Description:
Uses bullmq to have a job that periodically syncs the current prices.
Test plan:
1. `make reset-dev` to restart the containers,
2. After they are up, enter the database CLI with `yarn docker db`
3. Check on the current prices by entering `SELECT * FROM Price WHERE timestamp=0;`
4. Observe the `updatedAt` field: it should be changing every minute.
Depends on:
=> [Issue #301] feat: refresh current prices periodically

.gitignore, constants/index.ts, jobs/initJobs.ts, jobs/workers.ts, scripts/docker-exec-shortcuts.sh, scripts/paybutton-server-start.sh, services/grpcService.ts, services/transactionService.ts
Solves #88. Creates #346.
Addresses are now subscribed when they are added, such that if a new transactions appears on any address, it is automatically added to the DB.
**Test plan:**
After building, create a paybutton with of **your** addresses. Then, using [Electrum ABC](https://github.com/Bitcoin-ABC/ElectrumABC) or any other XEC wallet, transfer some small quantity to that address. After the transaction is confirmed, it should appear on  the button detail. Same thing with Bitcoin Cash.
Depends on:
=> [Issue #88] feat: automatic detect payments

.eslintrc.js, constants/index.ts, next.config.js, package.json, pages/api/address/transactions/[address].ts, pages/api/paybutton/index.ts, services/addressService.ts, tests/unittests/addressService.test.ts
Description:
Code to be used by #378. PR intended to facilitate the review process.
Test plan:
Depends on:
=> [Issue #154] feat: dependencies for select wallet when creating paybutton

components/MenuItem/index.tsx, components/Sidebar/index.tsx, components/Wallet/WalletCard.tsx, pages/payments/index.tsx, pages/wallets/index.tsx
addressing https://github.com/PayButton/paybutton-server/issues/392
Modified the nav links to be able to open in new tabs. Also added some tweaks to clear some console errors
=> [Issue #392] bug: Open nav links in new tab

prisma/seed.ts, prisma/seeds/addressUserConnectors.ts, prisma/seeds/addresses.ts, prisma/seeds/paybuttonAddressConnectors.ts
Description:
Populate the `AddressesOnUserProfiles` table when seeding.
Test plan:
=> [Issue #395] feat: seeds for user address connectors

constants/index.ts, pages/button/[id].tsx, services/networkService.ts, yarn.lock
Description:
Solves #433. Also added two other small changes for minor stuff that was bothering me:
- `yarn.lock` was out of date
- `COULD_NOT_GET_BLOCK_INFO_500` was missing the `_500`
Test plan:
#433 shouldn't happen anymore.
=> 1  [Issue #433] fix: paybutton undefined on view and minor chores

components/Wallet/EditWalletForm.tsx, components/Wallet/WalletForm.tsx, prisma/migrations/20220715134600_init/migration.sql, prisma/schema.prisma, prisma/seeds/addressUserConnectors.ts, prisma/seeds/addresses.ts, prisma/seeds/paybuttonAddressConnectors.ts, services/paybuttonService.ts, services/transactionService.ts, services/walletService.ts, tests/integration-tests/api.test.ts, tests/mockedObjects.ts, tests/unittests/walletService.test.ts, tests/utils.ts, utils/validators.ts
Description
---
Part of https://github.com/PayButton/paybutton-server/issues/264. Uses UUID on `Address` instead of autoincrementing ids.
Test plan
---
Run make reset-dev. Nothing should effectively change.
=>  [Issue #264] feat: use UUID on Address

prisma/seeds/addressUserConnectors.ts, prisma/seeds/networks.ts, services/networkService.ts, tests/unittests/networkService.test.ts
Description
---
Part of #422. Add a method to see what are the available networks for any user.
Test plan
---
The method is actually not being used anywhere, but it's covered by the tests.
=> [Issue #422] feat: get user networks

services/chronikService.ts, services/grpcService.ts
Description
Implements blockchain client chronik: sync transactions 
Test plan
1. Create new button with address (http://localhost:3000/buttons): ecash:qp0kfg0uk64k4pa7tw226djx4v30attzzslrec0ypu
2. Change ’grpc’ to ‘chronik’ for XEC in `constants/index.ts`, like this:
export const NETWORK_BLOCKCHAIN_CLIENTS: KeyValueT<BLOCKCHAIN_CLIENT_OPTIONS> = {
ecash: `'chronik'`,
bitcoincash: 'grpc'
}
3. Visit: http://localhost:3000/api/address/transactions/sync/ecash:qp0kfg0uk64k4pa7tw226djx4v30attzzslrec0ypu
This will use chronik to sync this address transactions and you will see 5 new transactions if you query the database or open the button you created in step 1.
=> 411_4_2 chronik sync transactions

package.json, pages/api/address/balance/[address].ts, services/blockchainService.ts, services/chronikService.ts, services/grpcService.ts, tests/unittests/validators.test.ts, yarn.lock
Description
---
Updates the prisma module.
Test plan
---
Recreate the containers, run the tests. Should work with no issues.
Remarks
---
This actually solves #479. Initial sync of txs should be way faster now.
=> chore: update prisma

components/Paybutton/PaybuttonDetail.tsx, components/Paybutton/PaybuttonList.tsx, components/Paybutton/paybutton.module.css
Description
Adding the currency icons to the buttons page and individual button page. 
Test plan
Go to the buttons page, and button pages and see if all of the buttons have the correct currency icon next to the name. Try adding some new ones or editing addresses
=> [Issue #470] Add currency icons to buttons page

components/Paybutton/EditButtonForm.tsx
Description
The current values of the button as a placeholder in the form was not ideal as it would disappear if new text was entered. 
Changed it to be the actual value for the inputs so a user can edit it more easily
Test plan
Try editing a button name and addresses and see if it works better and is easy to use
=> [Issue #466] Improve edit button form ui

constants/index.ts, jobs/workers.ts, pages/api/dashboard/index.ts, redis/dashboardCache.ts, services/addressService.ts, services/chronikService.ts, services/grpcService.ts, services/priceService.ts, services/transactionService.ts, tests/unittests/priceService.test.ts, utils/validators.ts
Depends on 
---
Description
---
Changes the caching so that it does it by address instead of by user.
Test plan
---
Caching should work as it was in #485. That is, works for the first sync but doesn't update.
=> [Issue #264] feat: cache by address not by user

.github/pull_request_template.md, prisma/seeds/devUser.ts
Description
---
Supertoken updated and it broked our dev user seeding. This fixes that
Test plan
---
Simply tests should pass.
=> fix: add new columns to raw query

jobs/workers.ts, sse-service/client.ts, sse-service/server.ts
Related to #545
Description
---
Fixes the automatic syncing of txs. 
Test plan
---
Before, adding a new address would not sync its txs. The page would be forever "Syncing transactions..."
Now it should sync it automatically and with no refresh required.
=> [Issue #545] fix: import of config in sse

.eslintrc.js, pages/button/[id].tsx, scripts/docker-exec-shortcuts.sh, services/chronikService.ts, services/grpcService.ts, sse-service/client.ts, sse-service/server.ts, utils/index.ts, utils/validators.ts
Related to #567
Depends on
---
Description
---
Solves #567.
This is also part of the client plan to change from periodic requests to SSE connection to our server. Now the connection can be made based on the address and, therefore, the button can use it.
Test plan
---
All should work normally as before: e.g. receving a tx should result in it appearing without the need to refresh the button detail page.
=> [Issue #567] feat: tx broadcast is address based

pages/api/dashboard/index.ts, redis/dashboardCache.ts, services/transactionService.ts
Related to #574
Description
---
Solves all problems of #574.
Test plan
---
Reset the containers and then test if all issues on #574 are not happening anymore.
In special, check that after a transaction is confirmed, you don't have two equal payments in the Payments page.
=> fix: dashboard payments cache problems

services/grpcService.ts
Description
---
Remove the deleting of unconfirmed txs in GRPC, txs should be simply updated to confirmed.
=> fix: no need to delete unconfirmed txs

components/Account/ChangePassword.tsx, constants/index.ts, pages/api/user/password/index.ts
Description
---
Fixes the non functional Account Change Password and displays supertokens default requirement to user on front end.
Test plan
---
Changing password should work, and require a password that is at least 8 chars long and has a letter and a number.
=> fix: account change password

components/Account/ChangePassword.tsx, components/Account/account.module.css, components/Paybutton/paybutton.module.css, components/Sidebar/index.tsx, pages/account/account.module.css, pages/account/index.tsx, styles/landing.module.css
Related to #
Description
---
Cleaning up the accounts page UI and added new icon for the nav
fyi I also snuck in a few random css tweaks for unrelated items while I was thinking of them (dark mode input text colors on button form mainly)
Test plan
---
Run the app and check out the account page, and try updating your password
=> Feat/accounts page UI

components/Account/ChangePassword.tsx, components/Account/account.module.css, components/Auth/ForgotPassword.tsx, components/Auth/ResetPassword.tsx, components/Auth/SignIn.tsx, components/Auth/SignUp.tsx, components/LandingPage/Footer.tsx, components/LandingPage/GetStarted.tsx, components/LandingPage/Hero.tsx, components/LandingPage/Navbar.tsx, components/MenuItem/menuitem.module.css, components/Network/NetworkList.tsx, components/Network/network.module.css, components/Paybutton/EditButtonForm.tsx, components/Paybutton/PaybuttonForm.tsx, components/Paybutton/paybutton.module.css, components/Wallet/EditWalletForm.tsx, components/Wallet/WalletForm.tsx, pages/account/account.module.css, pages/account/index.tsx, pages/dashboard/dashboard.module.css, pages/dashboard/index.tsx, pages/verify/index.tsx, styles/global.css, styles/landing.module.css, styles/signin.module.css
Description
---
Adding some more consistency to all of buttons in the app 
Test plan
---
Run through the app in both themes and check the buttons look good and are consistent throughout
=> UI: Improve button consistency

pages/account/account.module.css, pages/account/index.tsx
Description
---
I lost some changes in a failed rebase (still don't know how exactly), this brings back the changes about the secret keys on the Accounts page.
Test plan
---
=> fix: bring back secret on account page

components/ButtonGenerator/CodeBlock.tsx, components/ButtonGenerator/button-generator.module.css, components/ButtonGenerator/index.tsx, package.json, yarn.lock
Description
---
Adding a package to hightlight the code snippets on the button generator, as well as some logic to remove default or empty values from the code snippets
Test plan
---
Run the app and check out the button generator
=> UI: Button generator code format

pages/api/address/balance/[address].ts, pages/api/address/transactions/[address].ts, pages/api/address/transactions/sync/[address].ts, pages/api/price/[networkSlug]/[quoteSlug].ts, utils/index.ts
Related to https://github.com/PayButton/paybutton/issues/248
Description
---
Adds CORS to the `price/` endpoint.
Test plan
---
Prod is running this rn, so requests fro other domains to the `price/` endpoint shouldn't error.
=> [C#248] fix: cors on price endpoint

components/LandingPage/Footer.tsx, components/LandingPage/Navbar.tsx
Description
---
Updates landing page GitHub links to point a level up, rather than pointing to the client repo.
=> Link to main GitHub page.

package.json, yarn.lock
Related to #
Description
---
Updates PayButton.
Test plan
---
=> chore: update paybutton react

components/Paybutton/PaybuttonTrigger.tsx, scripts/docker-exec-shortcuts.sh
Test plan
---
Check /button/xxx page and dev script.
=> Fixed typos.

components/Paybutton/EditButtonForm.tsx
Related to #682 
Depends on
---
Description
---
Fixes #682 
Test plan
---
Try editing a button and pressing enter to submit the changes, should work on all fields except addresses & description where a line break happens instead.
=> #682 fix: enter key confirms button edit

components/Dashboard/Leaderboard.tsx, components/TableContainer.tsx, pages/api/dashboard/index.ts, pages/dashboard/dashboard.module.css, pages/dashboard/index.tsx, redis/dashboardCache.ts
Related to #685
Description
---
Implements #685:
Test plan
---
After loading the branch, reset the cache with `yarn docker cmr` and check if the leaderboard appears normally.
=> [#685] feat: buttons leaderboard

components/Transaction/AddressTransactions.tsx, components/Transaction/transaction.module.css, styles/global.css
Related to #698
Description
---
Fixes #698. 
Test plan
---
**Before:**
**After:**
=> [#698] fix: space between addresses txs

components/Dashboard/Leaderboard.tsx, pages/dashboard/index.tsx
Depends on
---
Description
---
Remove "Active Networks" column from the Button Leaderboard.
Test plan
---
The column shouldn't be there.
=> feat: no active networks column

components/LandingPage/Navbar.tsx, components/Layout/index.tsx, components/MenuItem/index.tsx, components/Page/index.tsx, components/Sidebar/index.tsx, constants/index.ts, pages/index.tsx
Related to #601
Description
---
Better navigation to the Landing Page when logged in.
Test plan
---
[As commented](https://github.com/PayButton/paybutton-server/issues/601#issuecomment-1751412650)  in #601,  make sure  all work fine.
=> [#601] feat: better logged in landing page navigation

components/Dashboard/Leaderboard.tsx, components/TableContainer.tsx, components/Transaction/AddressTransactions.tsx, pages/payments/index.tsx
Related to #716
Description
---
Adding a sorting function to be used on numeric table columns to ensure they sort properly 
Test plan
---
Run the app and check the leaderboard, payments, and individual button pages sort the amounts columns properly
=> [#716] UI: fix numeric table sorting

components/TableContainer.tsx
Related to #
Description
---
Fixing the two lint errors the table container component is throwing
Test plan
---
Run the app and check the tables still work as normal
=> Fix table lint errors

prisma/migrations/20231020131938_address/migration.sql, prisma/schema.prisma, services/addressService.ts, services/transactionService.ts, tests/mockedObjects.ts
Related to #660
Description
---
Part of #660. Adds a column "syncing" to better know if addresses have been synced to completion; adds a function to get transactions paginated.
Test plan
---
App should build normally and nothing should change.
=> [#660] feat: big address sync improvement deps

styles/global.css
Related to #734
Description
---
Greying out pagination buttons when they are disabled
Test plan
---
Preview the site and check out a table with multiple pages
=> [#734] UI: Pagination buttons disabled styles

docker-compose-prod.yml, services/transactionService.ts, tests/unittests/transactionService.test.ts
Description
---
Fix docker production start file and error where broadcast & confirmation in different days would lead to issues.
=> Fix: supertokens mysql version & price connection 

components/Admin/RegisteredUsers.tsx, pages/admin/index.tsx, services/userService.ts
Related to #747
Description
---
Fixes #747.
Test plan
---
Hard to reproduce, since #747 would only happen if there are 100+ users. Make sure that the page still works normally when running locally.
=> [#747] fix: admin page

components/Layout/layout.module.css, styles/global.css
Related to #743
Description
---
There was some CSS causing scrollbars not to appear. removing it here 
Test plan
---
preview the site and check scrollbars are present
=> [#743] ui - show scrollbars

prisma/seeds/addressUserConnectors.ts, prisma/seeds/addresses.ts, prisma/seeds/paybuttonAddressConnectors.ts, prisma/seeds/paybuttons.ts, prisma/seeds/walletUserConnectors.ts, prisma/seeds/wallets.ts
Related to #
Description
---
Adds a new `Dev` address, paybutton  & wallet.
Test plan
---
=> chore: new address automatically seeded

prisma/seed.ts, prisma/seeds/addressUserConnectors.ts, prisma/seeds/addresses.ts, prisma/seeds/paybuttonAddressConnectors.ts, prisma/seeds/paybuttons.ts, prisma/seeds/triggers.ts
Description
---
Added some seeds regarding my development experience, to avoid having to create that data everytime I want to test the POST return trigger.
Test plan
---
Should build normally.
=> chore: add seeds for better development related to triggers

services/chronikService.ts, tests/unittests/chronikService.test.ts
Depends on
---
Description
---
String substitution to make naming consistent:
nonce -> paymentId
Nonce -> PaymentId
Test plan
---
Nothing Should change
=> refactor: rename nonce -> paymentId

services/chronikService.ts, services/grpcService.ts, services/transactionService.ts, services/triggerService.ts, tests/unittests/chronikService.test.ts, utils/validators.ts, ws-service/server.ts, ws-service/types.ts
Related to #811 
Description
---
this  PR changes the broadcast data sent via socket to be cleaner
=> feat: update transaction payload

constants/index.ts
Related to #828 
Description
---
Set max page size limit to 2000
Test plan
---
Run server locally with `docker-compose up `and access (http://localhost:3000/address/transactions/ecash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek?pageSize=1000
)
=> feat: increase page size limit

Makefile, package.json, services/chronikService.ts, yarn.lock
Related to #
Description
---
Updates `chronik-client` to the latest version and refactors the code so we can use our in-node Chronik instance.
Test plan
---
1. Change `chronikClientURL` in the `paybutton-config.json` to `"https://xec.paybutton.io"`
2. Restart the containers.
3. Make sure it all still runs smoothly.
=> Chore: update chronik node

constants/index.ts, pages/api/paybutton/transactions/[id].ts
Related to #803 
Description
---
Added endpoint to fetch transactions by paybuttonId
Test plan
---
- Create a button with at least two adresses
- call route `http://localhost:3000/paybutton/transactions/{paybuttinId}
- Make sure the transactions returned are the same you see in the button page
=> feat: get tx by paybuttonId

pages/button/[id].tsx, styles/global.css
Related to #803 
Depends on 
---
-  #841
Description
---
Added a button to the paybutton page to donwload as all txs from that button in a CSV. 
Test plan
---
- Run the project with docker compose up 
- Go to your paybutton page and click Export as CSV, make sure the values are correct 
- Test with a paybutton with one address 
- Test with a paybutton with more then one address
=> feat: button download txs

docker-compose-prod.yml, docker-compose.yml
Test plan
---
Make sure build continues to work as expected.
=> Deprecated yml version line removed

pages/api/paybutton/download/transactions/[paybuttonId].ts
Related to #847 
Description
---
Changed value decimal places to 2
Test plan
---
Run server with docker compose up, go to button page, download CSV and check value column
=> fix: value fixed decimal

pages/account/account.module.css
Related to #880
Description
---
Fixing super long button under 'whats this' on account page 
Test plan
---
=> [UI] fix button width

components/Paybutton/PaybuttonTrigger.tsx, components/Paybutton/paybutton.module.css
Related to #
Description
---
Some style updates for the payments triggers section as discussed 
Test plan
---
Preview the site and check everything looks good and functions well
=> [UI] Payment Triggers UI Improvements

jobs/workers.ts, redis/dashboardCache.ts, services/transactionService.ts
Related to #
Description
---
Fixes the production error that would happen regularly: "No prices found for tx..."
Test plan
---
This is a weird bug, hard to be tested. I couldn't reproduce in the localhost, it would only happen in production.
Investigating, I found this issue in which many people report the bug, the maintainers have difficulty reproducing, but then someone finds a solution: https://github.com/prisma/prisma/issues/13713#issuecomment-1318439301
In any case, prod is already running it, so the error shouldn't happen anymore.
=> fix: missing prices

components/ButtonGenerator/index.tsx
Description
---
Fixed prop disable not applying correctly in Button Generator
Test plan
---
Run server with docker compose up, 
go to button generator click advanced and test disabled prop
=> fix: disabled generator prop

components/Paybutton/EditButtonForm.tsx, components/Paybutton/PaybuttonDetail.tsx, components/Paybutton/PaybuttonList.tsx, components/Paybutton/paybutton-detail.module.css, pages/button/[id].tsx
Related to #929
Description
---
Visual refresh and code refactor for the button cards seen on /buttons and /button/id pages
- consolidated code to one component for both pages
- ui tweaks
- added copy address functionality
Test plan
---
Preview and check out the button pages. Try copying some addresses
=> ui: Updates to button cards

.gitignore, redis/dashboardCache.ts
Related to #945
Description
---
Simplified and fixed the dashboard logic
Test plan
---
"All" and "Year" were differing about the last 12 months, should be equal now.
=> [#945] fix: dashboard incongruent info

components/Auth/ForgotPassword.tsx, components/Auth/ResetPassword.tsx, components/Auth/SignIn.tsx, components/Auth/SignUp.tsx, config/backendConfig.ts, config/frontendConfig.tsx, docker-compose-prod.yml, package.json, pages/admin/index.tsx, pages/api/user/password/index.ts, services/userService.ts, yarn.lock
Related to #955
Description
---
Fixes sing up issue due to out-of-date Supertokens.
This PR includes all the necessary migrations together with the updated package declarations.
Test plan
---
Already running on prod.
=> [#955] fix: passwords do not match error

services/chronikService.ts
Description
---
Small improvements to the chronik messages logs
=> feat: better chronik logs

.github/workflows/on-push-master.yml
Description
---
Fixes failing tests on master "on push" workflow.
=> fix: master workflow

components/TableContainer/TableContainerGetter.tsx, components/Transaction/PaybuttonTransactions.tsx, services/transactionService.ts
Description
---
If a Button were created with an address that has 0 transactions, the page would error. This PR fixes that.
Test plan
---
Create a PayButton having only one address, with no txs history. Make sure it would error in master but work here (no need to restart containers)
=> fix: button detail for 0 txs

.github/coding-instructions.md
Description
---
Adds a general project coding instructions file for Copilot to better understand what we want it (and anyone else working on the project) to do / not do.
This is just a starting point. We want to promptly add things that are specific to our project too (eg. Technologies used, coding standards chosen, etc).
Test plan
---
Try Agent Mode in your editor (eg. VS Code) and make sure Copilot's actually using the instructions.
Remarks
---
Currently, Copilot doesn't always read the instructions file every single time so you will have more luck if you open it in your editor and have it as the context when you're using Agent Mode.
=> Add Copilot instructions file
