.env
README.md
server/utils/bchd.ts

Add a simple way to be able to change bchd grpc node url: just set the GRPC_NODE_URL variable in a .env file.

feat: Support alternative BCHD installation (as an option)

---

.github/workflows/conventional-commits.yml

Add a github action to run on every Pull Request to ensure the commit messages follow the [Conventional Commits Spec](https://www.conventionalcommits.org/en/v1.0.0/)

chore: add github action to enforce commit style

---

config/backendConfig.ts
config/frontendConfig.tsx
next.config.js

WARNING: Facebook it's a demo app, so only added testers may login.
Apple uses supertokens.io demo account, remember to change to one of ours in the future.

feat: add Apple and Facebook authentication

---

next.config.js

fix: subdomain parsing
Description: Switching from replace to replaceAll to replace all occurences
in cases of "feat/add-button/1" -- one or more slashes
Test Plan: check if feat-add-button-1.paybutton.io or branches similar to this
are working fine in their domain

fix: subdomain parsing

---

components/PayButton/PayButtonsList.tsx
components/PayButton/index.tsx
pages/api/button/[id].ts
pages/api/button/index.ts
pages/index.tsx
types/index.ts

Description: This module provides a simple API for creating and getting PayButtons.
Test Plan: After clicking Add PayButton on the signed-in index page, it will show on console the response.
Also, after adding a PayButton, a simple list of added buttons with corresponding addresses will be shown on the signed-in page.
Depends on: feat/add-button/2

feat: Add PayButton [Part 3] (API)

---

Dockerfile
Makefile
README.md
docker-compose.yml

Description: 
- Removes MySQL image and volumes from docker-compose **for now**: it doesn't spin up containers in some contexts , **a separate PR will be made with new and tested configuration using mariadb image.**
-  Update README with information regarding credentials (otherwise, currently, the app wont start)
-  Update Makefile with proper docker-compose commands
Test Plan: 
- add credentials to .env or .env.local file
- run `make dev`
- app should be visible on http://localhost:3000

fix: docker-compose, makefile and update README

---

config/backendConfig.ts
config/frontendConfig.tsx

Description:
- Fix issue where, without all social login credentials, app would crash
- Now app will add only available social logins, if none, only email/password will show up on sign in/sign up page.
Test Plan: 
`make dev` and then run without social login credentials, add some social login credentials and run `make dev` again. 
app should be available at http://localhost:3000 with only available credentials, or only email/password.

fix: run app with available social login credentials

---

docker-compose.yml

Description: Adds mariadb (mysql drop-in replacement) to docker-compose file
Test Plan: run `make dev` and then `docker ps` to see if `db` container is up and running

feat: add mariadb (mysql drop-in replacement) to docker-compose

---

.github/CODEOWNERS

Adding @Klakurka and @Gattaca1 (and me) as reviewers automatically on GitHub

chore: add codeowners file to add reviewers automatically

---

Makefile

Description: adds `make check-logs-dev` and `make check-logs-db` to run commands to follow logs from paybutton-server container and db container.
Test Plan: run `make dev`, then each of the commands described above and see if logs are shown properly.

chore: add check logs commands to makefile

---

.env
Makefile
config/backendConfig.ts
docker-compose.yml

Description: adds supertokens (users service) local instance
Test Plan: 
- Remove existing SUPERTOKENS_API_KEY and SUPERTOKENS_CONNECTION_URI from your .env.local or .env file
- Run `make dev` **(`make stop-dev` first if containers already running)**  and then: 
- Open up http://localhost:3567/hello on you browser, there should be a 'Hello' text on the page.
- Sign up with email and password, and run `make check-logs-users`, there should be something similar to this:

Chore/add users service (supertokens local instance)

---

components/AddPayButtonForm.tsx
db/models/paybuttons.js
db/models/paybuttons_addresses.js
pages/api/paybutton/index.ts

Filling form and clicking the **Submit** button now commits the newly created paybutton and its addresses to the database.
There is no validation being performed on these addresses (if the string before the colon is a valid chain, if the text field is not empty, etc); I'll do that in the next PR.
I am also mocking the user because I couldn't get their ID right now, so I'll also solve that in a different PR.

Save paybutton & addresses on the  database

---

jest.config.js
package.json
yarn.lock

Added [ts-jest](https://github.com/kulshekhar/ts-jest) package to repository, allowing now the creation of unittests.
Test plan: create some file with `.test.ts` extension with some test such as:
```
test('example', () => {
expect(1+1).toBe(2)
});
```
then run `yarn test` on the node container.

Add unittests support

---

Makefile
docker-compose.yml

Description: Add named containers, updating Makefile accordingly. This fixes an issue where some operating systems would create a container with a different name (e.g. paybutton_server instead of paybutton-server) and would fail to run `make check-logs[...]` due to this mismatch.
Test Plan: `make dev`, then `make check-logs-dev`, `make check-logs-db`, `make check-logs-users`, see if logs are being printed accordingly.

ci: add named containers and update Makefile

---

components/ErrorBoundary/index.tsx

Description: Fix lint/ts-standard issues on ErrorBoundary component
Test Plan: `npx ts-standard components/ErrorBoundary/index.tsx` should show no linting errors.

fix: lint for error boundary component

---

constants/index.ts
services/paybuttonsService.ts
tests/unittests/validators.test.ts
utils/validators.ts

Description:
Part of #33: Creates functions to parse the new fields, plus their unittests. In this PR, the fields still don't exist. Thus, the validators created are are still not being used.
Test plan:
All tests should pass.

Feature: Add paybutton `name`, `uuid` and `buttonData` fields — Create parsers

---

prisma/migrations/20220609133700_add_name_hash_data_fields/migration.sql
prisma/schema.prisma

Part of #33: Creates the migration & updates the prisma scheme, adding the new fields.
- The `uuid` field is `VARCHAR` and not `UUID` because [prisma does not support UUID](https://www.prisma.io/docs/concepts/database-connectors/mysql#native-type-mappings) for MySQL yet.
- The `buttonData` field is set to NOT NULL so that null values are saved as `'{}', and thus even empty values can be parsed as JSON.
**Test plan:**
This, on its own, breaks all previous code related to the PayButton API & DB services, as well as their tests. The changes to that code will be added in subsequent PRs that point to this one as their dependency.
However, it's possible to test the migrations and the scheme by running:
```
yarn docker migratereset
yarn docker prismagenerate
```

Feature: Add paybutton name, uuid and buttonData fields — Create scheme & migrations

---

services/paybuttonsService.ts
tests/mockedModels.ts
tests/unittests/paybuttonsService.test.ts

Description:
Part of #33: Makes the necessary changes related to the new added fields to  `paybuttonsService.ts` and its tests.
Depends on:
Test plan:
The API & tests will be addressed in another PR, so those tests will fail. `yarn docker t tests/unittests/paybuttonsService.test.ts` should succeed.

Feature: Add paybutton name, uuid and buttonData fields — Change paybuttonsService

---

Dockerfile
docker-compose.yml

Description: fix for #121 **and other permissions issues**. It removes the multi-stage build since it was giving us too many permission issues to deal with, and workarounds on it, wasting time.
Test Plan: `git clean -fdx`, `docker rm -f $(docker ps -aq)`, `make dev`, then `make check-logs-dev` should show the server booting up. Prisma seeding issues will be fixed on #129.

fix: remove USER node and chown -R on prisma

---

prisma/schema.prisma

Description:
Prisma was weirdly creating migrations that did nothing. It was detecting that something had changed with the `Paybutton.uuid` field, then creating a migration to make the DB match the scheme. But the migration did nothing besides redefining `Paybutton.uuid` to exactly what it already was, so if you would try to run migrations again, it would do exactly the same thing over and over.
Test plan:
Run `yarn docker m` , it shouldn't prompt to create a new migration

Fix prisma creating multiple migrations.

---

pages/api/paybutton/index.ts
tests/integration-tests/api.test.ts

Sending a POST request with the `buttonData` attribute containing an invalid JSON would return a 500 error, instead of the controlled 400 error.
This PR fixes that and adds a test for it.
**Test plan:**
The integration tests already cover it.

Fix: Invalid button data error & test

---

constants/index.ts
package.json
pages/api/paybutton/index.ts
tests/integration-tests/api.test.ts
tests/unittests/validators.test.ts
tests/utils.ts
utils/validators.ts
xecaddrjs.d.ts
yarn.lock

Solves #145. Validation is now done by the `xecaddrjs` module. Now addresses without the chain prefix are accepted and their network is inferred, whenever possíble.
Remarks:
Since the functions in `xecaddrjs` do not differentiate the `bchreg` from the `bchtest` networks, an unprefixed test BCH address is interpreted as of the type `bchtest`. 
**Test Plan:**
All must be covered by the tests.

[Issue 145] refactor: validate addresses with `xecaddrjs`

---

.github/workflows/build-and-publish-container-image.yml

Description: related to #79, one of the necessary steps is to build and publish our container image to our github registry.
Test Plan: check github actions/checks tab and see if workflow runs successfully.

[Issue 79] ci: add github action workflow to build and publish container image

---

Makefile
package.json

Sometimes the github checks would fail with the following error message:
```
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "grpc-bchrpc-node: failed network integrity check".
```
This happened because the `grpc-bchrpc-node` module [client constructor](https://github.com/simpleledgerinc/grpc-bchrpc-node/blob/f26e8b3bc8e45c0a96bb73756298fc4a50754e51/src/client.ts#L32) checks for the network integrity automatically upon the declaration of a `new GrpcClient`, and if it fails, it tries to print the message `"grpc-bchrpc-node: failed network integrity check"`.
Since this check is not optional and it's coded in the `GrpcClient` constructor, mocking the method `_checkNetworkIntegrity` does not work, because the …

Fix: add --forceExit flag to ignore pending log issue on gh test actions

---

.env.development
config/appInfo.ts
next.config.js
pages/api/transactions/[address].ts

Description: Related to #141 (and will help #79), also enables changing api base path if needed (as in api.paybutton.org without subfolders for example).
Proper local environment variables available on `.env.development`
Test Plan: `make dev` should work as usual, adding different environment values on `.env` should break the website/change accordingly (e.g. if you are running on a local server or just changing `hosts` file to map to another domain. Or different subfolders.)

[Issue 141] feat: optional domain for api/app and base path configuration

---

prisma/seeds/networks.ts
prisma/seeds/paybuttons.ts

Solves #200 by making `ecash` the network with `id == 1` and the BCH seed address to have `networkId: 2`
**Test plan**:

[Issue #200] fix: seeds networkId

---

jest.config.js
tests/mockGrpcClient.ts
tests/mockedObjects.ts
tests/setupMocks.ts
tests/unittests/grpcService.test.ts

Description: related to #169 #195 and many others. This PR adds a mock for GrpcClient, enabling more test cases for the API, removing the need for the `rewire` library or other workarounds.
Test Plan: `make dev`, then `yarn docker test`. All tests should pass. No network integrity error should appear in the logs.

test: mock GrpcClient from grpc-bchrpc-node

---

package.json
yarn.lock

Description: cleaning up some unused dependencies.
Related to #131.
Test Plan: `make stop-dev`, rebuild paybutton image without cache to be sure (might take a while): `docker-compose build --no-cache paybutton`, then `make dev`. Frontend should stay the same.

[Issue #131]: remove unused dependencies mui-material and data-driven-forms

---

components/Sidebar/index.tsx

Improvement to close the mobile menu when a nav item is selected.
Test plan: Run the app in desktop and mobile size and ensure the menu works as intended

[Issue #215]feat:close mobile menu when item is clicked

---

pages/api/dashboard/index.ts
services/addressesService.ts
tests/integration-tests/api.test.ts

Description:
Create an API endpoint to retrieve data to be used in the dashboard.
Test plan:
This is not implemented in the front end yet (will be done in a separate PR), but it can be tested by running:
`curl http://localhost:3000/api/dashboard | jq`
Remarks:
- Dummy prices are being used instead of fetching the actual prices at the time of the transaction, which will be addressed in a future PR.

[Issue #151] feat: Create dashboard API endpoint

---

prisma/migrations/20220825134419_transaction_hash_and_address_unique_together/migration.sql
prisma/schema.prisma
services/transactionsService.ts

Description:
Solves #219 
Test Plan:
Create a button for the address [qzchtgjam2fs68tunggjgvf9h7v9yuv0dqal9p5pcs](https://ecashexplorer.com/address/ecash:qzchtgjam2fs68tunggjgvf9h7v9yuv0dqal9p5pcs). Then log out & back in to sync the transactions: two transactions should appear:
On master, only the first one would have appeared.

[Issue #219] fix: change uniqueness of Transaction hash -> hash & addressId

---

prisma/migrations/20220831141824_transaction_block_height/migration.sql
prisma/schema.prisma
services/transactionsService.ts
tests/mockedObjects.ts

Description:
Related to  #222, adds the `blockHeight` field to the `Transaction` table.
Test Plan:
`make reset-dev` then, after logging in in the front end to sync the transactions, run `curl http://localhost:3000/address/transactions/ecash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek| jq` and check if the `blockHeight` is also included.

[Issue  #222] feat: add transaction blockHeight field

---

prisma/migrations/20220831141824_transaction_block_height/migration.sql
prisma/schema.prisma
services/transactionsService.ts
tests/mockedObjects.ts

Description:
Undoes #229. #229 was build on the supposition that transactions were fetched from oldest to lastest; since the contrary is actually the case, solving #222 is much easier, see [this comment](https://github.com/PayButton/paybutton-server/issues/222#issuecomment-1234419829).
Test Plan:
None.

[Issue #229] fix: revert addition of blockHeight field

---

prisma/seeds/devUser.ts

Description:
Now the projects creates two users automatically: dev@paybutton.org and dev2@paybutton.org
Test Plan:
`make reset-dev`
Try to log in as `dev2@paybutton.org` with password `dev`

[Issue #234] feat: add second dev user to prisma seed

---

constants/index.ts
pages/api/transactions/[address].ts
prisma/schema.prisma
services/grpcService.ts
services/transactionsService.ts
tests/integration-tests/api.test.ts
tests/unittests/grpcService.test.ts
tests/unittests/transactionsService.test.ts

Description:
Part of #222. Makes so that all transactions of some address are fetched and added to our DB in chunks.
Test plan:
- Create a button for some address with significantly many transactions, e.g: [this address](https://ecashexplorer.com/address/ecash:qrv5hwntl5h4mypkg5kek6cj5f2d764txysuu0wffd) has 399 transactions,
- Log in and out to make it sync the transactions, and wait for it.
- Check the database to see if the numbers match:
- Enter the docker container database with `yd db`,
-   Get all transactions for newly created address:
```
MariaDB [paybutton]> SELECT * FROM Transaction where addressId=3;
[...]
399 rows in set (0.001 sec)
```

[Issue #222] feat: sync transactions in chunks

---

components/Paybutton/EditButtonForm.tsx
components/Paybutton/PaybuttonForm.tsx
components/Wallet/EditWalletForm.tsx
components/Wallet/WalletForm.tsx
pages/buttons/index.tsx
tests/unittests/validators.test.ts
utils/validators.ts

Description:
Renames `POSTParameters` to `paybuttonPOSTParameters`. With the addition of the `Wallet` model and the need to create a `walletPOSTParameters` (not in this PR), it was confusing to have a "generic" `POSTParameters`.
Test plan:

Refactor/ POSTParameters -> paybuttonPOSTParemeters

---

constants/index.ts
pages/api/paybutton/index.ts
tests/integration-tests/api.test.ts
tests/unittests/validators.test.ts
utils/validators.ts

Description:
Renames variable
`NAME_ALREADY_EXISTS_400` -> `PAYBUTTON_NAME_ALREADY_EXISTS_400`: because there will also be a `WALLET_NAME_ALREADY_EXISTS_400` in a future PR, so this makes it all more clear.
Test plan:

Refactor/ rename error message constant

---

prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
services/walletService.ts
tests/unittests/walletService.test.ts

Description:
The unique constraint for the wallet name was mentioning "Paybutton" instead of "Wallet". Furthermore, the `$transaction` call was also not working and it was fixed.
Test plan:

[Issue #154] fix: wallet constraint name & prisma transaction

---

prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
prisma/seed.ts
prisma/seeds/devUser.ts
prisma/seeds/walletUserConnectors.ts
services/walletService.ts
tests/integration-tests/api.test.ts

Description:
Creates the `UserProfile` and `WalletsOnUserProfile` tables.
`UserProfile` is a table for storing user settings. `WalletsOnUserProfile` is a connector model that connects multiple wallets to an user and defines which one of them are default and for which network through the field `isDefaultForNetworkId`.
Test Plan:
Nothing should change, one can explore the newly created model instances with:
```
$ yarn docker db
MariaDB [paybutton]> SELECT * FROM UserProfile;
MariaDB [paybutton]> SELECT * FROM WalletsOnUserProfile;
```

[Issue #154] feat: UserProfile and WalletsOnUserProfile tables

---

services/addressService.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/addressService.test.ts
tests/unittests/walletService.test.ts

Description:
Adds services & tests for addresses and wallets payment info (balance, # of payments). Necessary for displaying the actual wallets info in http://localhost:3000/wallets (to be implemented in a next PR).
Test plan:
Should be covered by the tests.

[Issue #154] feat: payment info services

---

components/Layout/layout.module.css
pages/auth/[[...path]].tsx
pages/button/[id].tsx
styles/global.css

A couple edits to center the login box and make the back button on the /button/id page go back to the page you came from instead of always back to the /buttons page

[Issue #271, #272] bug: center login box, change button back behavior

---

components/Wallet/WalletCard.tsx
pages/wallets/index.tsx

http://localhost:3000/wallets now shows the real wallets in the database.
**Test plan:**
Should be covered by the tests.
Nonetheless, the reviewer can create paybuttons and then wallets and see if the information is making sense. Check #263 `curl` POST example to see how to create a wallet.
**Remarks:**
- The function to edit the wallets, accessible when clicking in the pencil icon, has not been addressed in this PR and is not expected to work;
- The `default_wallet` is not implemented, so the `wallets` endpoint is returning all wallets as if this property was `false`. This also will be addressed in a next PR.
**Depends on:**

[Issue #154]: Wallet front end list

---

components/Wallet/EditWalletForm.tsx
constants/index.ts
pages/api/wallet/index.ts
services/walletService.ts
tests/integration-tests/api.test.ts
utils/validators.ts

Description:
Provides functionalities and fixes needed for subsequent PRs that will implement the wallet editing on the back end.
- Creating a wallet now also creates the `WalletsOnUserProfile` connector (there is one for each wallet);
-  Also, it creates the `UserProfile` if it does not already exists.
- Cannot create a wallet if one of the paybuttons belongs to another user.
Test plan:
Should be covered by the tests.
Depends on:

[Issue #154] feat: wallet edit back end defaults deps

---

components/Wallet/EditWalletForm.tsx
components/Wallet/WalletCard.tsx
pages/wallets/index.tsx

Description:
- Refresh wallets list upon pressing the **Submit** button, when editing a wallet
- Some other refactors needed for upcoming functionality 
Test plan:
At http://localhost:3000/wallets, when editing a wallet, clicking on the submit button should now close the modal (and reload the wallets).

[Issue #154] refactor: wallet edit form refresh & button id list

---

pages/api/dashboard/index.ts
pages/dashboard/Chart.tsx
pages/dashboard/index.tsx
tests/integration-tests/api.test.ts
utils/general.ts

Adding an all option to the dashboard charts. Also fixed a few bugs that were causing sub $0.01 transactions to not register, and causing some date misalignments in the charts 
Test plan: Run the app and test out the all button, and see if the transactions line up on the chart

[Issue #246] feat: 'All' option for dashboard charts

---

components/Wallet/EditWalletForm.tsx
pages/api/wallet/[id].ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/utils.ts

Description:
More requisites to the PRs that will implement the wallet functionality in the front end.
Test plan:
Creating a wallet, e.g. with:
```
curl -X POST localhost:3000/api/wallet -H "Content-Type: application/json"  -d '{"userId": "dev-uid", "name":"otherwallet", "paybuttonIdList":[6] }'
```
now returns the wallet with its paybuttons & addresses.

[Issue #154] refactor: createWallet returning model with related fields; test objects

---

config/backendConfig.ts
services/walletService.ts
tests/unittests/walletService.test.ts

Description:
Upon registering, new users have now a wallet being created for them, set as the default for both XEC & BCH.
Test plan:
Log out, create a new user, confirm the email. A empty wallet should be there:

[Issue #306] feat: create default wallet for user

---

components/Network/NetworkList.tsx
constants/index.ts
pages/api/networks/index.ts
services/grpcService.ts
services/networkService.ts

Description:
Solves #155. Shows network info in the front end.
Test plan:
Go to http://localhost:3000/networks and see if the info is there. Then mess up something of the `.env` file, run `make reset-dev` and see if it shows "Disconnected" for the messed up network(s).

[Issue #155] feat: showing networks connection info

---

pages/api/transactions/[address].ts
pages/api/transactions/sync/[address].ts
services/addressService.ts
tests/integration-tests/api.test.ts
tests/mockGrpcClient.ts
tests/unittests/addressService.test.ts

Description:
Create a new endpoint `http://localhost:3000/transactions/sync/[address]` to sync transactions for an address.
Test plan:
Run `curl http://localhost:3000/transactions/sync/[address-that-does-not-exist-in-the-database] | jq`. It should create the `Address` object & its transactions on the database and respond with the addresses transactions.
Furthermore, the endpoint `curl http://localhost:3000/transactions/[address]` now should return `404: No address found.` if run with an address that is not present on the database.

[Issue #171] feat:sync transactions endpoint

---

components/Paybutton/PaybuttonDetail.tsx
pages/api/paybutton/[id].ts
services/paybuttonService.ts
tests/integration-tests/api.test.ts
tests/unittests/paybuttonService.test.ts
tests/unittests/validators.test.ts
utils/validators.ts

Description:
Create API endpoint to edit paybuttons. No front end for accessing it implemented yet.
Test plan:
Tests should be covering it. There will be a next PR implementing the front end logic that depends on this one and makes testing from the front end possible; `curl` commands won't work because of the supertokens session authentication.
~Depends on:~ 
~- [ ] #318~

[#Issue 317] feat: edit paybuttons backend

---

components/Paybutton/PaybuttonForm.tsx

Description:
The 'addresses' field when creating a paybutton now always accepts multiple addresses.
Test plan:
Go to http://localhost:3000/buttons, try to create a paybutton. Everything should work as before, though it always now accepts more than one address.

refactor: create button always with multiple addresses

---

.env.development
.gitignore
config/appInfo.ts
docker-compose.yml
package.json
redis/clientInstance.ts
redis/redis.conf
scripts/docker-exec-shortcuts.sh
yarn.lock

Description:
Part of #322. Add redis to our project so we can later add [bullmq](https://github.com/taskforcesh/bullmq).
Test plan:
1. After pulling, first run `make reset-dev`
2. After all containers are up, inside the project directory run `yarn docker c` to enter the redis command line.
3. Run `KEYS *`. It should be empty.
Now, we are going to try to modify the redis cache from within our Next.JS project:
1. Create a file `test.patch` inside the project directory with the following content:
```
diff --git a/pages/api/dashboard/index.ts b/pages/api/dashboard/index.ts
index 6953f9d..f03287f 100644
--- a/pages/api/dashboard/index.ts
+++ b/pages/api/dashboard/index.ts
@@ -5,6 +5,7 @@ import { XEC_NETWORK_ID, BCH_NETWORK_ID } from 'constants/index'
import { Prisma } from '@prisma/client' …
```

[Issue #332] feat: add redis

---

Dockerfile

Fixes the:
```
Error: Unable to require('/home/node/src/node_modules/@prisma/engines/libquery_engine-linux-musl.so.node')
Error loading shared library libssl.so.1.1: No such file or directory (needed by .../node_modules/prisma/libquery_engine-linux-musl.so.node)
```
error.

fix: add openssl1.1-compat to alpine node container

---

Dockerfile
docker-compose.yml
package.json
redis/clientInstance.ts
scripts/paybutton-server-start.sh
services/transactionService.ts
utils/validators.ts
yarn.lock

Description:
Dependencies for next PR implementing the use of Bullmq to initially sync transactions & prices.
Test plan:
Nothing should change, the project should build and work normally as before. 
Remarks:
- Added `tmux` to the `node` container, so that the jobs are run separately from NextJS without the need of another docker container,
-  Added `ioredis` as the client for Redis as recommended/done on the Bullmq documentation/codebase,
- Added `tsx` as a mean to execute `.ts` files (`ts-node` does that too, but has a lot of caveats and needs for workarounds while `tsx` works much better out-of-the-box)

[Issue #301] feat: dependencies for bullmq for tx sync

---

config/backendConfig.ts
docker-compose.yml
scripts/paybutton-server-start.sh

Description:
`set -e` to exit the script if any of the lines failed was causing problems on some builds. I  rewrote it to acheive the same behavior without `set -e`.
Test plan:
If your build was working, it should continue working. If not, due to some `set: line 2: illegal option -` error, now it should work.

refactor: exit if any command fails without `set -e`

---

package.json

Description:
The repo's default logic is to expect local variables on `.env.local`, not `.env`. The command `yarn initJobs` has been adjusted accordinly.
Test plan:
Nothing should change, except that env vars on `.env.local`   such as `PRICE_API_URL` should now work for `yarn initJobs`.

fix: use .env.local instead of .env

---

prisma/seeds/addresses.ts
tests/mockedObjects.ts

Description:
Update Coin Dance BCH address on the seeded/mocked addresses.
Test plan:
None.

chore: update coin dance bch-address

---

components/Wallet/EditWalletForm.tsx
components/Wallet/WalletCard.tsx
pages/wallets/index.tsx
services/walletService.ts
tests/unittests/walletService.test.ts
utils/validators.ts

Description:
Editing wallets on http://localhost:3000/wallets now display errors on the modal, like it was already being done on http://localhost:3000/paybuttons.
Test plan:
Go to http://localhost:3000/wallets and try to modify an wallet in an invalid way, such as leaving it with no paybuttons or setting it as a default for some network which it has no addresses to.
Remarks:
- Fixed problem where was possible (on the backend) to set wallet with no XEC addresses to BCH default and vice e versa;
-  This edit feature still does not allow editing the wallet paybuttons, so that any unexpected behaviors related to it are still expected.

[Issue #154] feat: edit wallet show errors

---

constants/index.ts
prisma/seeds/networks.ts
services/grpcService.ts
services/networkService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/grpcService.test.ts
utils/index.ts

Description:
Replaced every hardcoded string to denominate some network by its slug (such as `'ecash'`) with a constant that evaluates to the same string.
Test plan:
Nothing should change

Refactor/ replaced hardcoded slug strings for constants

---

.gitignore
Makefile
docker-compose.yml
redis/redis.conf
scripts/paybutton-server-start.sh

Description:
Solves #363 and #364.
Test plan:
After checking out on this branch, manually delete the `redis/dumb.rdb` since this is not gonna be done automatically by `make stop-dev` now. Then reset the containers and everything should work normally.

[Issue #363, #364] fix: Redis not persistent & Exit start script with error

---

pages/api/wallet/[id].ts
services/walletService.ts
tests/unittests/walletService.test.ts
utils/validators.ts

Description:
Solve #353. Update user method requires `userId`, which will be get from session. Now users are not allowed to craft a request that would allow them to edit a wallet with other users' buttons.
Test plan:
Covered by tests, editing wallets from the front end should work normally.

[Issue #353] fix: require userId to update wallet

---

components/Transaction/AddressTransactions.tsx
jobs/workers.ts
prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
services/grpcService.ts
services/transactionService.ts
tests/mockedObjects.ts
tests/unittests/transactionService.test.ts

Description:
Part of #349. Subscribes addresses also to unconfirmed transactions, so that they are synced as soon as they get into the mempool. For now, I decided showing if they are confirmed or not; will remove that in the PR that removes from the DB transactions that become invalid.
Test plan:
Same as #345, but now waiting for unconfirmed txs. Also, more detailed output now will be visible by running `yarn docker jobs` or examining the file `jobs/out.log`.
Depends on:

[Issue #349] feat: subscribe addresses to unconfirmed txs

---

package.json

Env variables can now be put both on `.env` and `.env.local`. `.env.local` overrides `.env`.
**Test plan:**
Experiment with having the
```
GRPC_BCH_NODE_URL=
GRPC_XEC_NODE_URL=
PRICE_API_URL=
```
environment variables on `.env` and/or `.env.local` and see if both are being taken into account and if the aforementioned hierarchy is being preserved; by checking `jobs/out.log` and seeing if it works normally or breaks.

fix: take .env into account when running jobs

---

Dockerfile

Please delete `node_modules` folder and docker images before testing everything with `make dev`.
I used a bigger starting docker image that runs in M1 in the end. Also, I believe it has some of the packages that were manually installed afterwards, I removed them.

bigger base image that has the necessary packages to run on M1 also

---

utils/validators.ts

Duplicated addresses now are removed.
Also, as a bonus, I trimmed each address, so space after or before each address does not produce an error anymore.

duplicated addresses removed, trimmed each address

---

Dockerfile

adding the flag --platform=linux/amd64 to the original dockerfile (before last PR: https://github.com/PayButton/paybutton-server/pull/373) works in M1

[Issue #376] fix: smaller alphine image that still runs on M1

---

next.config.js
package.json

I have a server which is much faster than the notebook from where I am currently working, but in order to use it remotely is necessary to change some environment variables.
For me not to be forced to keep unstaged changes, I can change this env variables by putting them on `.env.development.local`, which is `.gitignore`d.
This PR makes so that `.env.development` is actually taken into account.
**Test plan:**
Nothing should change on running it locally.

chore: allow dynamic dev WEBSITE_DOMAIN

---

.eslintrc.js
services/addressService.ts
tests/unittests/addressService.test.ts

Description:
Tough it sounds logical to always parse the address before upserting, I don't think this should be done on the `upsertAddress` service.
- Everywhere in the code where we call this function (which on master is actually only on `pages/api/address/transactions/sync/[address].ts:37`), we do it after parsing the address already.
- When implementing another feature that would use this service to upsert addresses before when creating a paybutton, I've found out that a lot of tests would fail, because now the addresses were being parsed everytime a paybutton was being created, even though that's not the desired behavior on the tests, because we don't use real addresses there. 
- The function is intended to upsert some address, so it really should do only that.
Of course addresses …

feat: don't parse address when upserting it

---

constants/index.ts
utils/validators.ts

Description:
Solves  #371 and #385.
Test plan:
On master, creating an empty wallet should be possible if there is at least one paybutton that is not greyed out (disabled). On this branch, it shouldn't.
Finally, the error message now should be `Paybuttons were not provided.`

[Issue #385, #371] fix: disallow empty wallet creation

---

components/Paybutton/EditButtonForm.tsx
components/Paybutton/PaybuttonForm.tsx
pages/buttons/index.tsx
tests/unittests/validators.test.ts
utils/validators.ts

Description:
Interfaces should have uppercase names, this refactor simply renames `paybuttonPOSTParameters` -> `PaybuttonPOSTParameters` and `paybuttonPATCHParameters` -> `PaybuttonPATCHParameters`.
Test plan:
N/A

refactor: rename interfaces to uppercase

---

components/Paybutton/EditButtonForm.tsx

Description:
Solves #393.
Test plan:
Go to some button detail view, try to edit and provide e.g. some invalid address. The error message should display in the bottom. This error message also should have disappeared if the modal was closed and then reopened.

[Issue  #393] feat: error handling on EditPaybuttonForm modal

---

.github/workflows/pull-request-lint-and-test.yml
Makefile
tests/integration-tests/api.test.ts
tests/unittests/walletService.test.ts

Solves #390.
There was a `describe.only` on the code, that was mistakenly commited by me on January. This would make so that most of the `walletService` tests didn't run.
I've removed it & made so that the unittests git action also checks for `describe.only`s and `it.only`s across the tests folder, failing the action in case they're found.
**Test plan:**
Can only be tested by pushing a branch which contains such `.only` statements to github, [here](https://github.com/PayButton/paybutton-server/actions/runs/4133291387/jobs/7143017250) is an example of me testing it before.

[Issue #390] test: avoid .only statements on tests from being committed

---

components/Wallet/EditWalletForm.tsx
components/Wallet/WalletForm.tsx
constants/index.ts
pages/wallets/index.tsx
services/walletService.ts
tests/integration-tests/api.test.ts
tests/unittests/walletService.test.ts
utils/validators.ts

**Description**:
Before, upon wallet creation, we would not allow a user to select paybuttons that already belonged to other wallets. Now this is possible, such that the selected paybuttons will be updated so that they belong to the new wallet.
Furthermore, users cannot "consume" other wallets by this process, i.e, create a new wallet that leaves some already existent wallet with no paybuttons.
**Test plan:**
Try to create a wallet, assure that is possible to override other wallets paybuttons', as long as they are left with at least one paybutton.
**Depends on:**

[Issue #154] feat: allow for wallet creation to override paybutton wallet belongingness

---

components/Wallet/EditWalletForm.tsx

Description:
Before, upon wallet edit, we would not allow a user to select paybuttons that already belonged to other wallets. Now this is possible, such that the selected paybuttons will be updated so that they belong to the new wallet.
Furthermore, users cannot "consume" other wallets by this process, i.e, create a new wallet that leaves some already existent wallet with no paybuttons. Neither can the user leave the edit wallet with no paybuttons: at least one paybutton must be selected
Test plan:
Try to edit a wallet, assure that is possible to override other wallets paybuttons', as long as they & the wallet being edited are left with at least one paybutton.
Depends on:

[Issue #154] feat: allow for wallet edit to override paybutton wallet belongingness

---

constants/index.ts
pages/api/addresses/index.ts
tests/integration-tests/api.test.ts

Description:
Some changes required by #396. Basically:
- API endpoint to fetch all of some user addresses & tests for it,
- A error message constant to say that the user has not selected any address
Test plan:
`curl http://localhost:3000/addresses?userId='dev-uid'`  should return all addresses of the main dev user.

[Issue #395] feat: remodel address to wallet on wallet creation dependencies

---

components/Wallet/WalletForm.tsx
components/Wallet/wallet.module.css
constants/index.ts
pages/api/addresses/index.ts
pages/api/wallet/index.ts
pages/wallets/index.tsx
services/addressService.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/unittests/walletService.test.ts
tests/utils.ts
utils/validators.ts

Description:
Also displays the buttons to which the addresses are related, upon creating a wallet.
Test plan:
Try to create a wallet, there should appears the addresses with their related buttons.
Depends on:

[Issue #395] feat: show addresses paybuttons on wallet creation

---

components/Wallet/EditWalletForm.tsx
components/Wallet/WalletCard.tsx
components/Wallet/WalletForm.tsx
pages/wallets/index.tsx
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/walletService.test.ts

Description:
Shows the paybuttons that belongs to a wallet by inferring them from the wallet addresses.
Test plan:
Go on to create a new wallet, select some address to it. See if all wallets now are correctly inferring their paybuttons.
Remarks:
- Now, editing a wallet will produce unexpected results. This will be later addressed in another PR.
Depends on:

[Issue #395] feat: remodel address to wallet on wallet card

---

components/Wallet/EditWalletForm.tsx
components/Wallet/WalletCard.tsx
components/Wallet/WalletForm.tsx
pages/wallets/index.tsx
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/walletService.test.ts
utils/validators.ts

Remove the logic of disallowing users to creating empty wallets.
**Test plan:**
Try to create an empty wallet. Try to create a wallet that 'consumes' another wallet by using all of its addresses. Both should work and result in an empty wallet in the end.
**Depends on:**
**Remarks:**
As specified on #399, updating wallets is currently broken. I am updating this PR before fixing that so I don't need to refactor all the code that will be deleted here anyways.

[Issue #407] feat: allow empty wallets

---

components/Paybutton/PaybuttonForm.tsx
pages/buttons/index.tsx
services/walletService.ts

Description:
Part of #395. Changing the type that includes a wallet associated paybuttons (since we are deleting this association) for the type that gets the paybuttons from the wallet addresses.
Test plan:
Only a refactor, nothing should change.

[Issue #395] refactor: remove deprecated WalletWithAddressesAndPaybuttons type

---

components/Wallet/EditWalletForm.tsx
pages/wallets/index.tsx
services/addressService.ts
services/walletService.ts
tests/mockedObjects.ts

Description:
Solves #420.
Test plan:
1. Log into `dev@paybutton.org` on a browser window and into `dev2@paybutton.org` on a private window.
2. Take any of the addresses that `dev` is using on one of their paybuttons and create a paybutton with it for `dev2`
3. Go to the wallets view on both users. On master (considering this PR dependencies were met) something like this would be seen:
(on the left `dev2`, on the right `dev`)
On this branch, this should be fixed:
Depends on:

3  [Issue #420] feat: do not show other users paybuttons on wallet

---

services/grpcService.ts

XEC Grpc client wasn't working, this fixes it.
**Test plan:**
On the `Networks` tab, eCash should show "connected"
Also, the initial transaction syncing should also be working now. It still doesn't quite solves #433 because looks like the initial transactions sync is not being completed because some other job is race conditioning it; so not all transactions will be synced. This will be addressed in another PR

[Issue #433] fix: ecash grpc client being recreated

---

components/Wallet/EditWalletForm.tsx

Solves #401.
**Test plan:**
Go to http://localhost:3000/wallets, create a wallet, assign some addresses to it. Then go on and delete it. The assigned addresses should be reassigned to the default wallets (XEC addresses to the XEC default and BCH addresses to the BCH default).
The delete button should not appear for default wallets (even if it did, the deletion would be blocked on the back end).

[Issue #401] feat: add button & modal to delete wallets

---

jobs/initJobs.ts
jobs/workers.ts
scripts/docker-exec-shortcuts.sh

Description:
Solves #441 
Test plan:
1. Run `yarn docker jr` to reset the jobs,
2. See with `yarn docker jw` if first the past prices are being synced and then the current prices are being synced repeatedly.
Remarks:
Initial syncying of ecash transactions is still not working, this will be addressed in a next PR

[Issue #441] feat: generalized job to sync prices

---

constants/index.ts
jobs/workers.ts
services/priceService.ts

Description:
Solves #433.
Turns out that sometimes DB transactions for setting the transaction prices were taking longer than 5s, which is the prisma default. This increases the timeout to 15s.
Test plan:
Run `yarn docker jr` to rerun the jobs, and check with `yarn docker jw` if no errors happened and all addresses were synced fine.
Remarks:
Since we already have a robust pipeline for setting all past prices, we shouldn't even be upserting these transactions prices. For that, I created issue #447

[Issue  #443] fix: initial txs sync

---

components/Wallet/EditWalletForm.tsx
pages/api/wallet/[id].ts
prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
prisma/seeds/addressUserConnectors.ts
prisma/seeds/walletUserConnectors.ts
prisma/seeds/wallets.ts
services/paybuttonService.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/walletService.test.ts
tests/utils.ts
utils/validators.ts

Description:
Part of #264.Uses UUID on wallets instead of autoincrementing ids.
Test plan:
First run `make reset-dev`. Then all related to wallets should work normally: deleting, creating, modifying, creating a paybutton setting it to a wallet...

[Issue #264] feat: use UUID on wallets

---

prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
prisma/seeds/addressUserConnectors.ts
prisma/seeds/devUser.ts
prisma/seeds/walletUserConnectors.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts

Description:
Part of #264. Uses UUID on `UserProfile` instead of autoincrementing ids.
Test plan:
Run `make reset-dev`. Nothing should effectively change.
Depends on:

 [Issue #264] feat: use UUID on userProfile 

---

jobs/workers.ts
prisma/seeds/prices.ts
services/grpcService.ts
services/transactionService.ts

Description
---
Some functions that deal with the creation of `Transaction` objects were being expected to receive the type of a `Transaction`, as a row inserted in the database as input. This is not accurate because that type contains an `id` field, that we don't know yet.
Besides that, the `addressId` was set to be a hardcoded 0, which I don't understand why but don't think is correct, since we are going to connect that transaction with some address upon its creation.
Test plan
---
For what I observed, the initial sync of transactions in master is broken again, only for XEC though. Makes this hard to test for improvements right now.
Remarks
---
Associated to # 264 because this is necessary for both the Transaction & Address remodeling of increment number ids to UUIDs.

[Issue #264] fix: create transaction input

---

services/priceService.ts

Description
---
When fetching missing prices in the DB, we were doing several requests, one for each missing day. This changes so that we do only two requests, one for the XEC and other for the BCH prices, then we fill the DB with the missing prices using those lists.
Also, `Promise.all` expects an array of promises, but it was receiving an array of arrays of promises, which mean that it was completing immediatly. So the job was marked as completed before it was actually completed, and the promises would only resolve later. This solves that.
Test plan
---
1. Remove the env variables from  `PRICE_API_TOKEN` from `.env.development.local`, which is sufficient to make the past price sync give errors.
2. Re run the tests with `yd jr` and watch with `yd jw`. In this branch, after the errors one …

feat: update past newer prices only one request

---

.gitignore
docker-compose.yml
jobs/initJobs.ts
jobs/workers.ts
redis/clientInstance.ts
redis/redis.conf
scripts/docker-exec-shortcuts.sh
scripts/redis-start.sh

Description
---
Create a dedicated redis DB to bullMQ. This way, when caching the dashboard data, they don't get mixed up.
Test plan
---
1. Reset the containers with `make reset-dev`.
2. See if the jobs are being normally executed with `yd jw` or peeking into the `jobs/out.log` file
3. Reset the jobs with `yd jr` and make sure they all run again.
Also, you can enter the redis command-line with `yd c`, then:
1. Running `KEYS *` should return nothing,
2. Running `SELECT 1` and `KEYS *` should return the keys related to bullmq.
Depends on
---

[Issue #248] feat: dedicated redis db to bullmq

---

constants/index.ts
jobs/workers.ts
pages/api/dashboard/index.ts
redis/dashboardCache.ts
scripts/docker-exec-shortcuts.sh
services/addressService.ts

Description
---
Refactors dashboard code in order to make updating the `Payment`s cache possible.
Test plan
---
The dashboard & payments views should work just as they did in master. Reset the cache with `yd cmr` to make sure it's building also works.

[Issue #248] refactor: update payments cache deps

---

jobs/initJobs.ts
jobs/workers.ts
pages/api/address/transactions/[address].ts
pages/api/address/transactions/sync/[address].ts
scripts/redis-start.sh
services/blockchainService.ts
services/chronikService.ts
services/grpcService.ts
services/transactionService.ts

Description
---
Removes the syncing of prices together with transactions. The reasoning for this is that the syncing was causing significant overload when syncing the transactions, and it was unnecessary, since our code is already supposed to have all prices synced upon build.
Test plan
---
Rebuild the codebase, it should function just as before (tho now a bit faster)
Remarks
---
- Now we only sync the codebase transactions after ALL prices have been syncing,
- Left `console.time` on the code to time how long is it taking to upsert the transacitions into the DB. I've noticed it takes significantly longer in the BullMQ jobs then when using the API. When we get reasonable upsert prices, I'll take it off.
Depends on
---

[Issue #264] feat: dont sync prices with transactions

---

components/TableContainer.tsx

Description
Setting the default table sort to the timestamp desc so latest transactions on top
Test plan
Go to payments page and see if its sorted correctly

[Issue #465] Default sort payments by date

---

jobs/workers.ts
services/chronikService.ts
services/grpcService.ts
services/transactionService.ts

Depends on
---
Description
---
Reformulated the logic responsible to upsert transactions so that transactions are created, not upserted. The difference, essentially, is that if we try to create a transaction that already exists, it will return an error (as it should, because we should not be reinserting transactions).
Test plan
---
Initial sync of txs should happen normally.

[Issue #479] feat/create transaction not upserting

---

constants/index.ts
jobs/workers.ts
services/priceService.ts
utils/validators.ts

Description
---
Solves #486 
Test plan
---
On master, spinning up the containers and entering the db container (`yarn docker db`), running the query:
```
select timestamp from Price order by timestamp desc limit 1;
```
...would give an old day equivalent to the most recent day in the `prisma/seeds/prices.csv` file.
In this branch, the same thing should give the today's date.
Remarks
---
Also makes so that the intial addresses sync is ignored if some tx is already found in the database (making it possible to rerun the jobs with no issue)

[Issue #486] fix: price sync up to today

---

constants/index.ts
jobs/workers.ts
redis/dashboardCache.ts
services/addressService.ts
services/chronikService.ts
services/grpcService.ts
services/priceService.ts
services/transactionService.ts
tests/unittests/priceService.test.ts
utils/validators.ts

Depends on
---
Description
---
When creating transactions, automatically connect them to the existent price.
Test plan
---
1. Spin up the containers
2. After all is up, add a new address that has some transactions on it. Make sure you see the transactions in the button detail view.
3. Enter the database with `yarn docker db`
5. The number returned by `SELECT COUNT(*) FROM PricesOnTransactions;` should be twice the number returned by `SELECT COUNT(*) FROM Transaction;`
Remarks
---
The rationale for this is so that the cached payments, that appear on the dashboard, can be updated as soon as a new transaction is inserted. This PR still does not acomplishes that yet, but makes so that the `createManyTransactions` and `createTransaction` functions return transactions already with it's …

[Issue #264] feat: connect prices when inserting transactions

---

prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
prisma/seeds/addressUserConnectors.ts
prisma/seeds/devUser.ts
prisma/seeds/walletUserConnectors.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts

Description
---
Changes the `UserProfile` table so its primary key is the same as the table in the `supertokens` table.
Before, if I had the `id` for a `userProfile`, I would have to fetch that info from the DB to get its `userId` just to e.g. see the wallets or addresses associated with it. Now `id` and `userId` are the same thing, which is what before was called `userId`.
Test plan
---

[Issue #491] refactor: user profile same id as supertokens

---

components/TableContainer.tsx

Description
Adding a localstorage value for the table page size so it persists across pages and on new visits. 
Also updated the pagesize values as per https://github.com/PayButton/paybutton-server/issues/495 
Test plan
Change the page size on some tables and refresh the page or navigate to another table to see if it remains on that size

[#Issue 495] feat: save last choice of table page size

---

constants/index.ts
services/chronikService.ts

Description
---
Subscribes to receive broadcast of new transactions in the blockchain (chronik client only). They should be added to our database at the same time as they happen in the blockchain, first as an unconfirmed transaction, then as a confirmed transaction when it confirms.
Also, this PR sets chronik as the blockchain client to be used for all XEC addresses.
Test plan
---
- add an address you control to the application (one that will receive the transfer)
- run: yarn docker c, then flushall, then exit
- run: yarn docker jr
- run: yarn docker jw
- transfer to the address in step 1
- run database select * from paybutton.Transaction, you will see your transaction added as unconfirmed fist, then as confirmed

411 6 2 chronik subscribe transactions implemented

---

Makefile

Description
---
Simply renames the make commands `check-logs-...`  to `logs-...`, which is shorter.

chore: rename `check-logs-...` to `logs-...`

---

components/Paybutton/EditButtonForm.tsx
components/Paybutton/PaybuttonDetail.tsx
constants/index.ts
pages/button/[id].tsx
redis/clientInstance.ts
services/addressesOnUserProfileService.ts
services/paybuttonService.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/mockedObjects.ts
tests/unittests/paybuttonService.test.ts
tests/utils.ts

Depends on
---
Description
---
Almost fixes #491 and #498: Updates the table `AddressesOnUserProfiles` when paybuttons are removed or created, but not when they are updated 
Paybutton update will be addressed in the next PR
Test plan
---
Create paybuttons, delete paybuttons, and check in the wallets view if the shown networks are correctly reflecting the addresses associated do the wallets through its paybuttons.

[#Issue 498, #491] feat: creating and deleting paybuttons updated address to user relation

---

.gitignore
jobs/workers.ts
redis/clientInstance.ts
services/chronikService.ts

Description
---
Makes so that the syncing jobs (the initial one and the one that runs on repeat) keep going if some address fails.
Test plan
---
As of now, the BCH address won't sync because the grpc node is out of service. Therefore, just see if the XEC addresses are synced normally, new XEC addresses also.
Remarks
---
This also removes some logs that we're spamming the next server output, those are the changes on the files `services/chronikService.ts`  and `redis/clientInstance.ts`.

[Issue #496] feat: keep jobs if some addr fails

---

pages/payments/index.tsx
styles/global.css

Description
Adding some styles to allow for multiple buttons to be on the same line in the button column on the payments page on larger screens. Currently they each are on new line if there are multiple buttons
Test plan
Run the app and see if the buttons column is no longer stacking multiple buttons

[Issue #494] UI - payments page button column

---

.gitignore
Dockerfile
docker-compose.yml
package.json
scripts/docker-exec-shortcuts.sh
scripts/init-sse-server.sh
scripts/paybutton-server-start.sh
sse-service/client.ts
sse-service/server.ts

Description
---
Part of #334.
Creates a dedicated server to send Server Side Events (SSE). In the next PR this will be used to send information to all clients viewing a paybutton page that one of their addresses has been updated, so that the transactions are refreshed live.
Test plan
---
1. Add a secret key to your `.env.local` file in the format: `SSE_AUTH_KEY=b5e38f40-0798-47ef-a4d2-1d6a41393af4`. I used the command `uuidgen` to get this example.
2. Restart the containers.
3. Listen to the server events with `curl -N http://localhost:5000/events`
4. Broadcast an tx event with e.g. `curl -X POST -H 'Content-type: application/json' -H 'X-auth-key: 71e4e0bf-976f-4408-9a7c-87bceab020a2' --data-raw '{"addressList": ["ecash:qzjg2tfdjlcm3hqy4vz2v08846a78v4mn586t0c27y"]}' …

[Issue #334] feat: Server side events server setup

---

jobs/workers.ts
services/chronikService.ts
services/grpcService.ts
services/transactionService.ts

Description
---
Solves #509.
The hash for txs fetched from chronik were incorrectly assumend to be base64, leading to invalid URLs for the block explorer
Also improves some error messages related to syncing txs bugs
Test plan
---
Rebuild the containers, check that the ecash txs URLs on the paybutton detail view are correct.

[Issue #509] fix: Tx hash on chronik

---

constants/index.ts
pages/api/paybutton/[id].ts
services/addressesOnUserProfileService.ts
services/paybuttonService.ts
services/walletService.ts
tests/integration-tests/api.test.ts
tests/unittests/paybuttonService.test.ts
tests/unittests/validators.test.ts
utils/validators.ts

Description
---
Solves #498, #491
Updates the table `AddressOnUserProfiles` when updating paybuttons.
Test plan
---
These changes simultaneously affects updating paybuttons & also wallets. Ideally, creating & deleting those should also be tested.
After updating a paybutton or a wallet with different addresses, it is expected that the network icon (that can show the XEC symbol, the BCH symbol, or both) is correctly immediately updated. This is not the case on master.

 [Issue #498, #491] feat: updating paybuttons updates address to user relation 

---

constants/index.ts
services/transactionService.ts

Description
---
Modify  the sync of txs so that reinserting txs that already exists in DB is accepted.
They are now upserted one-by-one, in parallel.
Test plan
---
Re run the containers, it should work normally.
Furthermore, large addresses now should sync to completion (no errors between the syncing conflicting with the subscription because of inserting a tx that arrived after the sync started), but since this takes a while, this should better be tested in the PR [WIP] that requires this one.

[Issue #513] feat: More incremental tx sync

---

components/Network/NetworkList.tsx
components/Network/network.module.css
components/Wallet/EditWalletForm.tsx
components/Wallet/WalletCard.tsx
components/Wallet/WalletForm.tsx
pages/api/networks/user.ts
pages/networks/index.tsx
pages/wallets/index.tsx
services/networkService.ts

Description
As per #422 hiding info and labels on networks not in use
Test plan
Run the app and remove all buttons. You should not see any network specific "default" labels on any wallet screens, and both networks should be visible in the networks tab
Next try adding one ecash address and you should see XEC labels in those places and the BCH network should be hidden in the networks tab
Next try adding a BCH address and check the same

UI hide unused networks

---

redis/dashboardCache.ts
scripts/paybutton-server-start.sh

Description
---
Solves #527
Test plan
---
No need to rerun containers, just delete the cache with `yarn docker cmr` and check that the negative payments are gone.

[Issue #527] fix: Only create payments for > 0 txs

---

config/appInfo.ts
pages/button/[id].tsx
services/chronikService.ts
services/grpcService.ts
sse-service/client.ts
sse-service/server.ts

Depends on
---
Description
---
Uses a env var to set up the SSE server.
Test plan
---
All should work normally due to the fallback. Nonetheless, for prod this can be changed by setting the `SSE_BASE_URL` var in the `.env.local` file.
You can try breaking it setting a dummy URL in this file, or in `.env.development.local` in case you don't have `ENV=production` in `.env.local`. Then reset the containers

fix: Env var for SSE

---

addresses
components/Transaction/AddressTransactions.tsx
jobs/workers.ts
pages/button/[id].tsx
services/chronikService.ts

Related to #432
---
Description
---
Distinguishes between having a button w no transactions and a button that hasn't been synced yet. This can be improved in terms of prettiness, right now I simply made so that the text "No transactions yet." is replaced by "Syncing address..." in the case that the address has not been synced yet.
Test plan
---
Create a new button and click on it right away. You should see:
(there is a small chance that the sync will happen just after you click the button and you will see "No transactions yet.")
This text should be replaced for the txs in case the address has txs and for the text "No transactions yet" in case the address has no txs. No refreshing of the page should be needed.

[Issue #432] feat: distinguish button syncing vs button with no txs

---

components/Paybutton/EditButtonForm.tsx
components/Wallet/EditWalletForm.tsx
components/Wallet/WalletForm.tsx

Description
---
Fixes problem in prod where some requests would have the repeated domain, e.g:
`https://api.paybutton.org/button/api.paybutton.org/api/paybutton/94f0a111-6f92-4eb2-b5c5-d3cc0b044973`
Test plan
---
E.g. creating wallets, editing buttons & deleting buttons should work normally locally, as it did before, and should work now on prod.

fix: do not use `websiteDomain` on axios

---

jobs/workers.ts
pages/api/address/transactions/[address].ts
pages/api/address/transactions/sync/[address].ts
services/transactionService.ts

Solves #539 
Description
---
Endpoint `address/transactions` now will also subscribe the addresses, so that we monitor them for when new txs arrive.
Test plan
---
This is running now in prod, so it should solve #539

[Issue #539] fix: no new txs on endpoint

---

services/addressService.ts

Description
---
Payment count on wallet was counting negative txs.
Test plan
---
Check that the payment count sum of wallets is different from the value in the dashboard. After this PR should be the same

fix: wallet payment count

---

jobs/initJobs.ts
jobs/workers.ts
services/paybuttonService.ts
services/transactionService.ts

Description
---
Address sync is now done through a job that polls for new addresses anymore.
Now, when a new address is inserted through button creation/ updating a button, we sync it asynchronously.
Test plan
---
Should work better than before:
- now its faster because there is no delay in waiting for the poll to detect the new address,
- now its async, a big address won't block new address from sync. New addresses will sync just as they are inserted.

feat: no job for sync addresses

---

constants/index.ts
jobs/workers.ts
services/chronikService.ts
services/grpcService.ts
sse-service/server.ts

Related to #565 
Description
---
We were getting errors in prod in trying to broadcast the upcoming transaction to the SSE server, which would break the subscription.
Now we log and ignore this issue if it happens.
Test plan
---
Querying for e.g. `https://api.paybutton.org/api/address/transactions/ecash:qqfttx62h6uqn73978rjatl680rccxfd5uuwyfp6nl`  should always return new txs if those exist. That means a button client should not stop receving txs updates.
Remarks
---
It's good that this CORS problem does not breaks tx subscription, but we should not be getting it anyway. This would be addressed seperately.

[Issue #565] fix: ignore tx broadcast issue

---

services/priceService.ts
services/transactionService.ts

Related to #572
Description
---
Solves #572 and also another bug where prices wouldn't be connected to new arriving addresses/txs.
Test plan
---
1. Restart the containers, then  go to the DB container and check the timestamp of today by running:
`select timestamp from Price order by timestamp DESC limit 4;`
e.g. on the day of writing this PR, this is `1689033600`.
2. Then delete those prices by running e.g.` DELETE FROM Price WHERE timestamp=1689033600;`
You should see: `Query OK, 4 rows affected`.
Running ` SELECT * FROM Price WHERE timestamp=1689033600;` should return nothing
3.  Now either add a paybutton that has a tx that was done today, or add any paybutton and make a tx to it.
4. In both cases, the tx should appear in the detail normally, the dashboard should work normally and now …

[Issue #572] fix: update prices on days passing

---

prisma/migrations/20220715134600_init/migration.sql
prisma/schema.prisma
services/chronikService.ts
services/transactionService.ts
utils/validators.ts

Related to #565
Description
---
#565 may be happening for other reasons, but right now I noticed on the logs that sometimes we were trying to delete non-existent txs. This PR fixed that
Test plan
---
1. Add two of your addresses to some paybutton, one of which has spendable coins.
2. Transfer money from one to the other. On ABC's wallet you can do that by right clicking an address and selecting "Spend from this address".
3. When the tx is confirmed, it should in parallel try to delete the unconfirmed tx twice. This makes so that we get the error "Record doesn't exist", but this can also not happen since async is non deterministic (one process can be executed quite further away from the other so that when it tries to find the unconfirmed tx this has already been deleted). This error should …

fix: only delete uncofirmed txs if they exist

---

config/index.ts

Description
---
Missing `-1` to get the last element of list, this would always lead to undefined

fix: always undefined const

---

config/backendConfig.ts
prisma/migrations/20230818181919_admin_user/migration.sql
prisma/schema.prisma
prisma/seed.ts
prisma/seeds/users.ts
utils/setSession.ts

Related to #538
Description
---
Enables the default user dashboard of supertokens and create an admin account for it. 
Test plan
---
Authenticate as the admin user at http://localhost:3000/api/auth/dashboard and try it out.

[#538] feat: add admin dashboard view

---

pages/account/account.module.css

Description
---
Taking out the css rule that was adding some extra margin to the h2 on the account page.
Test plan
---
run the app and go to /account. The title at the top should be in the same place as the other pages

Remove  unneeded margin

---

scripts/docker-exec-shortcuts.sh

Description
---
Our production environment encounters an error when using `yarn docker x` commands:
`./scripts/docker-exec-shortcuts.sh: 16: Syntax error: "(" unexpected`
Adding a `bash` shebang seems to be the easy fix.
Test plan
---
I haven't been able to recreate this outside of production. This test plan shouldn't cause downtime.
1. SSH into production server, and navigate to the server directory (should be on `master`)
2. Run `yarn docker dbs`
3. You will encounter an error
4. Now checkout this branch `git checkout fix/docker-script-compatibility`
5. Run `yarn docker dbs`
6. You should receive the db container prompt
7. Checkout `master` when finished testing

Fix - Docker Script Compatibility

---

.env.test
Makefile
constants/index.ts
services/chronikService.ts

Related to #
Description
---
Not setting a `WS_AUTH_KEY` now returns an error.
Test plan
---
Run the containers without the env var on .env or .env.local, you should get an error when trying to access the site for the first time.

chore: error if no WS_AUTH_KEY

---

components/Paybutton/PaybuttonDetail.tsx
components/Paybutton/PaybuttonTrigger.tsx
pages/api/paybutton/trigger/[id].ts
pages/button/[id].tsx
utils/validators.ts

Related to #613
Description
---
Adds a skeleton for the frontend that sets up the triggers.
Test plan
---
For now, the submitted info will be logged in the backend, nothing else.
The following PRs will validate, commit the trigger to the the database and do the actual trigger activation upon payment

[#613] feat: payment triggers frontend skeleton

---

config/example-config.json
config/index.ts
prisma/migrations/20230831194209_trigger_logs/migration.sql
prisma/schema.prisma
services/triggerService.ts
utils/validators.ts

Related to #613 
Description
---
Logs every trigger execution, regardless of if it failed or not.
Also makes so that the URL defined by the user is the one used.
Test plan
---
1. Add the line `  "triggerPOSTTimeout": 3000` to your `paybutton-config.json`. See the example in `config/example-config.json`. This will make the trigger post wait at most 3 seconds for an answer.
2. Create a trigger, for example, with URL `https://httpbin.org/post` and data `{ "myThing": <amount>, "other": <buttonName> }`.
3. Send a payment to that button
4.  Enter the docker db container  (`yarn docker db`) and run `SELECT * FROM TriggerLog;`, and see if it was all logged alright.
5. Then change that trigger URL, to e.g: `https://sitethatdefinitelydoesnotexist.com`, send another payment to some of the button …

[#613] feat: payment trigger logs

---

components/Paybutton/PaybuttonTrigger.tsx

Related to #613
Description
---
Hides "Receive email" checkbox on trigger form.
Test plan
---
Nothing should change, just shouldn't be possible to set this option on triggers, until we implement actually doing the email alert.

[#613] feat: payment triggers hide send email

---

jobs/initJobs.ts
jobs/workers.ts
prisma/clientInstance.ts
scripts/docker-exec-shortcuts.sh
services/blockchainService.ts
services/chronikService.ts
services/transactionService.ts

Description
---
Fix the problem where resetting the prod app would lose the subscriptions of addresses already in the DB (since the DB is not being reset)
Test plan
---
- Prod is already running this, so receiving live info about txs of any address that was subscribed before (or not) should work now.
- https://api.paybutton.org/status should list  all subscribed addresses, and this should be all `ecash` addresses in the DB.
One other test would be resetting prod and still having all addresses that were subscribed before subscribed now.
Remarks
---
This PR brings a variety of technical changes, so I'll list them here:
-  Jobs don't subscribe addresses, only sync their txs
- Fixes `yarn docker` commands to access remote DB
- Add `yarn docker` command to create dump of DB (this was unstaged …

fix: subscribe db addresses

---

jobs/initJobs.ts
jobs/workers.ts
pages/api/status/index.ts
prisma/clientInstance.ts
scripts/docker-exec-shortcuts.sh
services/blockchainService.ts
services/chronikService.ts
services/transactionService.ts

Depends on
---
Description
---
Makes `/status` endpoint secure by requesting WS_AUTH_KEY as a request paremeter.
Test plan
---
Accessing localhost:3000/status should return "unauthorised", in order to see the subscribed addresses one would have to send e.g. http://localhost:3000/status?secret=<WS_AUTH_KEY>  where `WS_AUTH_KEY` should be set on `.env.local`.

feat: secure status api

---

jobs/workers.ts
package.json
services/blockchainService.ts

Description
---
Jobs were still suscribing addresses, this fixes that this happens only on the NextJS app.
Test plan
---
There shouldn't  be anything about 'subscribring' in the `logs/jobs-out.log`.
Also, prod is running this branch and should be working normally

fix: jobs dont subscribe

---

prisma/migrations/20220715134600_init/migration.sql
prisma/migrations/20230905163432_nullable_provider_user_id/migration.sql
prisma/migrations/20230905163536_post_url_bigger/migration.sql
prisma/schema.prisma

Related to  #640
Description
---
Fix migration history: since we won't be resetting the DB anymore, I shouldn't had modified existent migrations.
Also solves  #640
Test plan
---
- `postURL` should hold more chars (255 instead of 191 max)
- Prod is running this branch, should be working normally

Fix:  separate migration, postURL size

---

constants/index.ts
services/paybuttonService.ts

Related to #661
Description
---
Prevents IFP addresses from being added or updated
Test plan
---
1. Try adding an IFP address to a paybutton - you should encounter an error
2. Try updating a paybutton to use an IFP address - you should encounter an error

Fix: block IFP addresses

---

components/ButtonGenerator/index.tsx

Related to #
Description
---
Remove alt currencies, (EUR, GBP, and AUD) from button generator
Test plan
---
run the app and check the button generator. See if alt currencies are gone

UI: Remove alt currencies from button generator

---

package.json
yarn.lock

Related to #657
Description
---
Sets `package.json` to always fetch the latest version of `@paybutton/react`.
Test plan
---

[#657] feat: use latest paybutton version

---

services/chronikService.ts

Related to #665
Description
---
Fixes issue where arriving negative txs wouldn't be registered.
Test plan
---
Necessary to reset the containers (chronik processing message function doesn't update at runtime with Next).
1. Create two buttons with two of your addresses,
2. Send some XEC from one to the other,
3. Make sure the tx appears in both buttons.

[#665] fix: don't ignore negative transactions

---

services/transactionService.ts

Related to  #673
Description
---
Tx confirmation now also updates the timestamp.
Test plan
---
Necessary to reset the containers.
Create a button with one of your addresses and send some XEC to it. See the timestamp when it's unconfirmed and check it again when confirmed, it should have updated (unlike in master)

[#673] fix: update timestamp when tx is confirmed

---

services/chronikService.ts
services/grpcService.ts
services/transactionService.ts

Related to #675
Depends on
---
Description
---
Broadcasts when txs are confirmed. Fixes #675  
Test plan
---
After rebuilding the app, make sure that when a new tx is confirmed the view at http://localhost:3000/button/[button-id]  is updated automatically without need for refreshing.

[#675] fix: confirm transaction incoming without refreshing

---

components/Paybutton/EditButtonForm.tsx

Related to #
Description
---
Updating the placeholder text for edit button form website and description to match the create button form
Test plan
---
Go to edit a button and check the right placeholder text is there

Fix: Edit button form placeholder text

---

constants/index.ts
prisma/seeds/users.ts
services/triggerService.ts
tests/unittests/validators.test.ts
utils/validators.ts

Related to #687
Description
---
Fixes #687. Don't allow the creation of empty triggers, which were resulting in error logs since there is nothing to execute.
Test plan
---
Try to create a trigger without setting an URL and a postData, should not be possible.
Remarks
---
This should be changed when we implementing receiving emails as a functionality of the trigger, but for now makes no sense allowing to create a trigger that does nothing.

[#687] fix: disallow empty string for post data

---

pages/button/[id].tsx
utils/index.ts

Related to #328
Description
---
Solves #328.
Test plan
---
When editing a button, make sure that:
- Editing **out** an address immediately **removes** its transactions from the button detail page,
- Editing **in** an address immediately **adds** its transactions to the button detail page,
- Editing some other paybutton detail (such as the name, for example) doesn't change the transactions (nor does it makes it flash/blink/refresh to the same thing).

[#328] feat: refresh addresses on button edit

---

components/TableContainer.tsx

Description
---
Minor change.
Table page selector:
... only appears if total pages is greater than 1.
Test plan
---
Check some tables (payments, button transactions, button leaaderboard if #692 is merged) and see if the page selector appears if and only if there is more than only the first page.

feat: only show page selector if > 1 pages

---

redis/dashboardCache.ts

Related to #695
Description
---
Fixes #695. Confirmation of txs would create a second Payment.
Test plan
---
It's necessary to reset the main container (paybutton-dev).
1. Send some XEC to some of your addresses and verify it appeared in the button detail and also in the Payments tab.
2. After the payment is confirmed, refresh the Payments tab and check that it doesn't have a duplicated entry for this payment.
In master the behavior is that it should create a second redundant payment for the confirmation.

[#695] fix: tx confirmation doesn't create another cache entry

---

Makefile
docker-compose-prod.yml
scripts/paybutton-server-start.sh

Description
---
On production, we should not spin up the container, since we use a remote db.
Test plan
---
Hard to test it thoroughly, one could manually create a remote DB and then configure `.env.local` with its credentials and run `make prod`. But running `make prod` without doing that should not create the 4 containers, only 3, and should then show an error about not being able to find the DB to connect.

chore: don't spin DB container on prod

---

components/Dashboard/Leaderboard.tsx
pages/dashboard/index.tsx

Related to #706
Description
---
Show filter info in leaderboard and remove redundant info.
Test plan
---
Make sure that the filter info is being shown in the leaderboard (**red**), and that the total revenue info (**yellow**) is not being redundantly shown in the **blue** area.

[#706] feat: filter info on leaderboard

---

components/Sidebar/index.tsx

Related to #601
Description
---
On mobile the PayButton logo was not redirecting to the landing page. The PR fixes that.

[#601] fix: on mobile, PayButton logo goes to landing page too

---

constants/index.ts
pages/dashboard/index.tsx
utils/cookies.ts

Related to #703
Description
---
Saves dashboard filter in cookie.
Test plan
---
Set some period on the dashboard. Refreshing the page, as well as logging out and back in, should not change the set period.

[#703] feat: save dashboard settings

---

components/Transaction/AddressTransactions.tsx
components/Transaction/transaction.module.css

Related to #207
Description
---
Adding an explorer link to the addresses at the top of the transaction tables on the button detail page
Test plan
---
Run the app and check out a button detail view. you should see the eye icon next to the address that should link to the explorer

[#207] Add explorer link to address label

---

components/Chart.tsx
components/Transaction/AddressTransactions.tsx

Related to #348 
Description
---
Adding some formatting to the usd values on the dashboard chart, and on the XEC and BCH values on the button detail transaction table. XEC values should force to 2 decimals and BCH to 8
Test plan
---
Run the app and check the numbers in those place to see if they look good

[348]ui: force decimals on amounts

---

components/LandingPage/Footer.tsx
components/LandingPage/LogoutButton.tsx
components/LandingPage/Navbar.tsx
pages/index.tsx
styles/global.css
styles/landing.module.css

Related to #655 #713
Description
---
Fixing the issue of the sign up button not showing in the footer, and also matching the new behavior of the navbar so dashboard and Sign out show in the footer when logged in. Also sniped the logo size to match in the navbar, footer, and dashboard views
Test plan
---
Run the app and check the footer links look good when logged in and not logged in

[#655, #713]UI: footer button and logo sizing

---

Makefile

Description
---
Changes `docker-compose` for `docker compose`.
Test plan
---
The changed make commands should work just as before.

chore: make file use `docker compose` instead of `docker-compose`

---

constants/index.ts
docker-compose-prod.yml
jobs/workers.ts
pages/signin/index.tsx
pages/signup/index.tsx
redis/dashboardCache.ts
services/chronikService.ts
services/transactionService.ts

Related to #732, #744
Description
---
Solves some bugs related to chronik and tx sync:
- Avoid duplicate calls when txs that are related to more than one address arrive.
For example, if a tx from address A to B is broadcasted and both addresses A and B are in our DB, the new tx pipeline will trigger twice and therefore run for both addresses twice. This PR introduces a 3s delay where txs that are already being processed won't be processed again. This won't conflict with other incoming transactions or arriving confirmations.
- Upon deploy connect transactions with one price to the missing second price
- Don't take the current month into account to consider the monthly time windows. This was accidentally done, such that in months with less than 31 days, payments that happened in the 31st of …

[#732, #744] fix: new tx pipeline

---

.gitignore
logs/.gitignore

Description
---
Instead of ignoring the `logs/` directory and risking getting permission issues when docker creates it; we simply ignore everything inside it while committing the dir itself, making sure its permissions are tracked by git.

chore: commit logs dir, empty

---

components/TableContainer/TableContainer.tsx

Related to #747
Description
---
Fixes #747
Test plan
---
Reproduce #747 in master, switch to this and make sure its gone. Make sure also that the page size is saved on the browser (not only for this admin table, but for all tables that use TableContainer, such as Payments, for example): switch for example to 25 items per page and make sure it still shows 25 items per page after refreshing the page.

[#747] fix: don't try to access browser storage when SSR

---

Dockerfile

Description
---
Fixes missing package error.

chore: openssl1.1 was deprecated

---

components/ButtonGenerator/button-generator.module.css
components/ButtonGenerator/index.tsx

Related to #751
Description
---
Adding the get address link back in to the button generator
Test plan
---
preview the site and check the link on the 'to' field works and looks good

[#751] UI: Add get address link to button generator

---

jobs/workers.ts
services/addressService.ts
services/chronikService.ts
services/priceService.ts
services/transactionService.ts

Related to #732
Description
---
Make so we sync the missed transactions one address by one, and log the errors in case there are any.
Test plan
---
This can be tested in local dev by:
1. Have the containers running with `make dev` and some of your addresses in the database.
2. Stop all containers but the database one with `make stop-prod`
3. Make sure the database is up and running with `yarn docker db` and check how many txs you have on that address of yours with `SELECT count(*) FROM Address where address='ecash:youraddresshere';`
4. Transfer some XEC to that address
5. Build the project with `make prod` and make sure that after it is up the newly arrived tx is synced, that same counting query should return one more entry.

[#732] fix: avoid tx holes

---

jobs/workers.ts
services/chronikService.ts

Related to #732
Description
---
Adds logic to run syncing job such that every tx is resynced.   This makes so that the one line diff:
```                      
--- a/jobs/initJobs.ts                                      
+++ b/jobs/initJobs.ts                                      
@@ -35,7 +35,7 @@ const main = async (): Promise<void> => { 
}                                                        
const flowJobSyncAndSubscribeXECAddresses: FlowJob = {   
queueName: initTransactionsQueue.name,                 
-    data: { networkId: XEC_NETWORK_ID },                   
+    data: { networkId: XEC_NETWORK_ID, fully: true },      
name: 'syncAndSubscribeXECAddressesFlow',              
opts: {                                                
removeOnFail: false, …
```

[#732] feat: possibility to fully sync addresses

---

components/Paybutton/PaybuttonTrigger.tsx
components/Paybutton/paybutton.module.css
pages/api/paybutton/triggers/[id].ts

Related to #772
Description
---
Implements the deletion of a trigger and improves the general trigger UX.
Test plan
---
Besides being able to delete triggers, the whole process of creating & updating them should be more clean and intuitive. Users can only update a trigger if in the form there is anything different than what was loaded; it also will refresh the form with the updated data instead of hiding it behind a success message (as it did before).

[#772] feat: delete triggers & better UX

---

constants/index.ts
prisma/migrations/20240111230813_tx_extra_data/migration.sql
prisma/schema.prisma
services/chronikService.ts
tests/mockedObjects.ts

Related to #774
Description
---
Implements the parsing of  [NULL DATA](https://learnmeabitcoin.com/technical/nulldata) (OP_RETURN) scripts on transactions.
Test plan
---
1. Restart the containers. Necessary to reload chronik.
2. Send a TX with ElectrumABC OP_RETURN field as `paybutton$anypieceofdatayouwant` to any address you have on the running app,
3. Use `yarn docker db` and then `select createdAt, hash, amount, extraData from Transaction where not extraData='';` to see which txs have some data on it. Besides the data for the just sent tx, there should  be some data for txs I already sent when developing this feature.

[#774] feat: basic OP_RETURN parsing

---

components/Paybutton/PaybuttonTrigger.tsx
services/triggerService.ts
utils/validators.ts

Related to #774
Depends on
---
Description
---
Adds <opReturn>  as a valid variable for setting up triggers.
Test plan
---
1. Create your trigger, use a website you control or a dummy one such as https://httpbin.org/post.
2. Make sure to include the variable in the trigger body, such as ` {"op": <opReturn> }` 
3. Send a tx to the address with OP_RETURN=`paybutton$anyDataYouWant` and make sure it appears in the receiving end of the POST request e.g. `{"op": 'anyDataYouWant'}`

[#774] feat: op return variable on triggers

---

scripts/paybutton-server-start.sh

Description
---
Right now the `paybutton-dev` container fails when trying to connect to the `paybutton-db` container the first times simply because the DB container takes longer to start.
This change makes it wait until it has started.
Test plan
---
Check that the containers start normally

feat: scripts waits for DB connection

---

services/blockchainService.ts
services/chronikService.ts
services/triggerService.ts
tests/unittests/chronikService.test.ts
tests/unittests/validators.test.ts
utils/validators.ts

Related to #774 
Depends on
---
Description
---
Parses the `opReturn` string conforming to the specs defined in https://reviews.bitcoinabc.org/D15176, and
adds the variable to the paybutton triggers.
Test plan
---
As discussed in https://github.com/PayButton/paybutton/issues/302; I've added a basic support for JSON and arrays.
If a PayButton, created using the branch in the linked dependency, is created with `op-return="key=value separated=by spaces=and arrays=are|done|this|way"`
This will should result in:
```
{
paymentId: '66c682719fb0e45e',
data: {
key: 'value',
separated: 'by',
spaces: 'and',
arrays: ['are', 'done', 'this', 'way']
}
}
```
Something not parsable such as `op-return="mySimpleText with an equal sign at the end to add confusion="` should then return:
```
{
paymentId: …
```

[#774] feat: op return new specs

---

tests/unittests/validators.test.ts
utils/validators.ts

Related to #774
Description
---
Allows the parsing of JSON strings.
Test plan
---
- If a paybutton is constructed with e.g. `op-return='{"my": "customData"}"`; we should be able to parse that into an object; that will later be broadcasted as 
```
{
my: 'customData'
}
```
... in a paybutton trigger.
- Also, I've added tests covering (what I thought to be) all the edge cases, if there is any weirdness missing from it please mention it.

[#774] feat: try to parse it as JSON

---

constants/index.ts
prisma/seeds/triggers.ts
ws-service/server.ts

Related to #774 
Description
---
Parses the OP_RETURN JSON data saved in the DB as a string to JSON before broadcasting.
I added error handling just in case, but this error should never happen since we should always save the `Transaction.opReturn` field either as an empty string (no op return) or as a JSON containing the keys `data` and `paymentId`.
Test plan
---
When a TX with a PayButton OP_RETURN happens; the server should broadcast it this field as a JSON not a string. When a tx without an OP_RETURN happens, then it should broadcast it as `null`.
This can be tested using a PayButton with a trigger containing the `<opReturn>`  variable.

[#774] feat: broadcast parsed op return

---

components/ButtonGenerator/CodeBlock.tsx

Related to #
Description
---
- changed the example to close the div to avoid errors 
- added indentation to the code
Test plan
---
Open the project, run the build `docker-compose up` and check the button generator if the html example is closing the div properly

fix(#801): close div properly

---

services/addressService.ts
tests/mockedObjects.ts
tests/unittests/addressService.test.ts

Related to #803 
Description
---
Added a service method to fetch addresses by paybuttonId
Test plan
---
Run project with `docker-compose up` make sure the project runs correctly,  check `yarn docker test` and  `yarn docker testcoverage` to analyse coverage reports

feat: get addresses by paybuttonId

---

constants/index.ts
services/priceService.ts

Description
---
When prices are missing, show exactly which prices are missing.
Test plan
---
- Apply the patch:
```
diff --git a/services/priceService.ts b/services/priceService.ts
index 83909493..1fd57617 100644
--- a/services/priceService.ts
+++ b/services/priceService.ts
@@ -224,7 +224,7 @@ export async function fetchPricesForNetworkAndTimestamp (networkId: number, time
Price_timestamp_quoteId_networkId_unique_constraint: {
quoteId: CAD_QUOTE_ID,
networkId,
-        timestamp
+        timestamp: timestamp +1
}
}
})
@@ -233,7 +233,7 @@ export async function fetchPricesForNetworkAndTimestamp (networkId: number, time
Price_timestamp_quoteId_networkId_unique_constraint: {
quoteId: USD_QUOTE_ID,
networkId,
-        timestamp
+        timestamp: timestamp +1
}
}
})
```
... to make the error …

feat: better error message for missing prices

---

prisma/seed.ts

Related to #
Description
---
Prod has this as unstaged changes in order to avoid having the users being created again, this is just a simple fix to that.
Test plan
---
Shouldn't alter dev, shouldn't alter prod either because it is already running with this, unstaged.

chore: don't seed in prod

---

pages/api/paybutton/download/transactions/[paybuttonId].ts

Related to #855 
Description
---
Shows currency unit on the `value ` header of the txs CSV
Test plan
---
CSV now should have `Value (USD)` as the header instead of `Value`.

feat: txs CSV value header shows units

---

constants/index.ts

Related to #860
Description
---
Preventing the sidebar from showing on sign in pages when navigating around 
Test plan
---
preview the site and check you cant cause the issue. It stopped happening for me all together so not sure if this solves it or not

[UI] Prevent sidebar when not logged in 

---

prisma/migrations/20240924181742_/migration.sql
prisma/schema.prisma
tests/mockedObjects.ts

Related to #619 
Description
---
Added `preferredCurrencyId` field to `UserProfile` scheme and generated a new migration
The `default` value for this field is 1 the id for **USD** quote.
Test plan
---
Make sure the field was added to the UserProfile entity with default 1

feat: add preferredCurrencyId field

---

constants/index.ts

Related to #870
Description
---
CSV max row count increased from 2k -> 10k.
Test plan
---
1. Create a button with the following addresses: `ecash:qp0g6tty4re6cqtttgus34s7ht80xvqndqtynvfhd9`, `ecash:qr6mxvfp2hlr0qg5phhqapqz8ajv7uaxk55z9332rl`, `ecash:qzgyg3llme32kpru03ff7dq7lz8087ma6glfxngvp2`, `ecash:qqhe60kagdq6fftrd2m2j62ygeyd7w26fvwlv0ntjk`, `ecash:qpp6zklxvwrqynkhlp75qszgcw0mdu8uuu55gjkvax`
2. Generate a CSV and see that it has >6000 txs.

Increased max CSV row count from 2k to 10k.

---

components/ButtonGenerator/button-generator.module.css
components/LandingPage/Navbar.tsx

Related to #874
Description
---
Adding a bit of spacing to the button generator link so it doesnt go under the nav when it scrolls to the section. 
Also improving the mobile menu on the landing page so it closes when an item is clicked
Test plan
---
preview the site and check it works

[UI] Add spacing to button generator anchor link

---

components/Account/ChangeFiatCurrency.tsx
components/Account/account.module.css
pages/account/index.tsx
pages/api/user/index.ts
services/userService.ts
utils/validators.ts

Related to #848
Description
---
Implements the logic to select the default currency between USD and CAD
Test plan
---
After resetting the containers, go to /account and make sure that the new currency selector works well and in fact updated the DB.

[#848] feat: referred currency setting

---

components/Chart.tsx
components/Dashboard/Leaderboard.tsx
pages/api/paybutton/download/transactions/[paybuttonId].ts
pages/dashboard/index.tsx
pages/payments/index.tsx
redis/balanceCache.ts
redis/dashboardCache.ts
redis/index.ts
redis/paymentCache.ts
redis/types.ts
tests/integration-tests/api.test.ts
tests/unittests/validators.test.ts
utils/index.ts
utils/validators.ts

Related to #848
Description
---
Implements the usage of the user prefered currency.
Test plan
---
1. Spin up the containers on **master**.
2. Switch the currency of the dev user to CAD. Checking out the dashboard then, should yield no difference.
3. Checkout to this branch. Still this should yield no difference
4. Now reset the cache. `yarn docker cr`.
5. Finally, the values in the dashboard and elsewhere should all be in CAD instead of USD (thus they will be significantly higher).

[#848] feat: use currency setting

---

services/chronikService.ts
services/transactionService.ts

Related to #830
Description
---
Fixes the slowness of inserting an upcoming tx in the db.
Test plan
---
In localhost this was not perceptible because there isn't that many addresses and txs, but if one were to add some big addresses, then it would become perceptible. In any case, prod is running this branch already, so this can be tested there.

[#830] Fix: slow tx refresh

---

pages/api/address/transactions/count/[address].ts
redis/dashboardCache.ts
redis/paymentCache.ts
redis/types.ts
services/addressService.ts
services/transactionService.ts
tests/integration-tests/api.test.ts

Related to  #540
Description
---
Fixes the long loading time for the button detail and the dashboard views.
Doesn't touch the payments view, for that will be fixed with #741.
Test plan
---
1. On master, add a huge address to the dev account and wait for it to fully sync. 
2. See how long the button detail and the dashboard take to load.
3. Now switch branches and try it again. Since the dashboard is cached, try also running `del dev-uid:dashboard` in the redis CLI to force the cache to be reacreated.
For me, recreating the cache took 2s with an address with 130k+ txs, compared to 30s+ in master.

[#540] fix: slow page loads

---

.githooks/pre-commit
components/ButtonGenerator/data.js
components/ButtonGenerator/index.tsx
components/Paybutton/paybutton.module.css

Related to #794 & #804
Description
---
Adding op return and disable payment id to the button generator
Also sneaking in a CSS tweak to prevent the wallet dialog from running off the page
Test plan
---
Check the button generator and check the create or edit wallet dialog in an account with lots of buttons

[UI] Add advanced button generator options

---

pages/api/payments/count/index.ts
redis/index.ts
redis/paymentCache.ts

Related to #741 
Description
---
Created a new endpoint to fetch the total amount of payments, it will be used in the paginate payments logic
Test plan
Run server, Log in the dashboard and try accessing this url : 
'http://localhost:3000/api/payments/count' 
It should retrieve the same amount of payments that is showing up in the dashboard

feat: get payments count

---

constants/mail.ts
services/triggerService.ts

Related to #
Description
---
Wraps up the mail transporter in the global var in order to avoid reconnecting to our mail host many times (during development).
Test plan
---
When running the dev environment in **master**, we would get many logs related to the mailer authenticating. Updating a file or refreshing a page would trigger all again.
In this branch, this should not be the case: refreshing a page or changing a file shouldn't result in these logs being shown again. Nonetheless, email triggers should work normally.

feat: wrap mailer on global

---

redis/dashboardCache.ts
services/transactionService.ts

Related to #896
Description
---
Dashboard on master was back to showing data, but it was all wrong. Payments would appear one month after they real date, and the view for **ALL** payments would include months with no payments in the beginning. This PR fixes these issues.
Test plan
---
On **master**:
1. Take any address with some payments, and check how on the dashboard they would be displaced: shifted one to the right, i.e, a payment from september would appear in october, for example.
2. Check how the **ALL** view in the dev user would include the months Dec2020 and Jan2021, with no payments. That is useless info that shouldn't be there, **ALL** should start from the first payment.
Then checkout this branch, run `yarn docker cr` to reset the cache and try it again — all the above should …

#896 fix/dashboard issues

---

docker-compose.yml
scripts/paybutton-server-start.sh

Description
---
Makes so that logs are not stored with errors separate from everything else (as is the default in `pm2`), which IMO has always made debugging a little more complex than it should be.
Test plan
---
Reset the containers, make sure everything starts normally and that the `logs/` don't contain two logs of each service anymore (e.g. `logs/jobs-out.log` and `logs/jobs-error.log`, but only one `logs/jobs.log`)

feat: merge stdout and stderr on logs

---

services/priceService.ts
services/transactionService.ts

Related to #905
Description
---
When adding a big address (like ecash:prfhcnyqnl5cgrnmlfmms675w93ld7mvvqd0y8lz07), if the syncing process encountered some missing prices, this would lead to the error mentioned on #905.
This PR fixes this error, by uncoupling the process of filling up the missing prices and connecting it to the transaction.
Test plan
---
On master, after restarting the containers, try adding the aforementioned address to a button. After adding 200 txs around 10 times, it should result on the error happening multiple times.
Then restart the containers again on this branch, it should work fine.

fix: price upsert error

---

pages/api/paybutton/download/transactions/[paybuttonId].ts
pages/button/[id].tsx

Related to #911 
Description
---
Added timezone logic to CSV creation
Test plan
---
Run the server with `docker compose up`
download CSV it should display the date according to the timezone set.

fix: add timezone to csv

---

services/chronikService.ts
services/triggerService.ts

Related to #762 
Description
---
Trigger logs wouldn't fire for coinbase transactions. This PR fixes this behavior.
Test plan
---
Make sure coinbase txs will fire a trigger. This is being run in prod for some time, so could've been tested there.
Remarks
---
I was holding this PR up to add tests with it, but since the tests will require some good amount of refactoring, I decide to put them up in a separate PR.

feat: coinbase tx trigger execution

---

services/chronikService.ts
services/transactionService.ts
ws-service/types.ts

Related to [#916]([https://github.com/PayButton/paybutton-server/issues/916])
Description
---
Send input addresses in broadcast incoming tx data, this will be used in paybutton client, this will make input addresses available on client callbacks 
Test plan
---
- Run server with docker compose up
- Run client in this PR https://github.com/PayButton/paybutton/pull/445
- Test if inputs are being returned as a param (inputAddresses) of tx object in onSuccess/OnTransaction callbacks

feat: broadcast input addresses

---

components/Account/ChangeFiatCurrency.tsx
components/Account/ChangePassword.tsx
components/Account/account.module.css
components/Organization/organization.module.css
components/Timezone Selector/index.tsx
components/Timezone Selector/timezone-selector.module.css
pages/account/account.module.css
pages/account/index.tsx

Related to #924
Description
---
I started to fix the currency select display, but the whole page needed some attention really. Here are some proposed ui edits to make the page design more cohesive 
Test plan
---
preview the site and check /account

ui: Improve account page UI

---

components/Paybutton/LoadingSpinner.tsx
components/Paybutton/PaybuttonForm.tsx
components/Paybutton/paybutton.module.css
pages/button/[id].tsx
styles/global.css

Related to #903
Description
---
Adding some loading state when creating a button or exporting a csv. Just went for the basic "Loading..." Could potentially do a spinner/animation if we want something fancier
Test plan
---
preview the site, and try making a button with several addresses and exporting a csv. Should see the button change to a loading state

[ui] Add loading state for button creation and export csv

---

Makefile
services/chronikService.ts
ws-service/route.ts
ws-service/sideshift.ts

Related to #937
Description
---
Fixes issue with sideshift where client requests were being proxied without their IP being properly passed in the headers.
Test plan
---
Already running in prod, should solve the blocked sideshift issue.
Remarks
---
- Add command `make deploy` to deploy production more easily.
- Removed empty tx broadcasting.

[#937] fix: sideshift user ip

---

.env.from-dump
.github/workflows/on-push-master.yml
Makefile
constants/index.ts
docker-compose-from-dump.yml
prisma/seed.ts
redis/paymentCache.ts
services/chronikService.ts
services/transactionService.ts

Related to #940 
Description
---
Mainly, this PR fixes some big prisma queries that were throwing errors in production.
Additionally:
- Adds a new make command `make reset-dev-keep-db` to reset only the dev container and keep the db intact
- Adds a new make commands `make dev-from-dump` to create a dev environment but instead of seeding, using a `dump.sql` file in the repo's root directory.
- Fixes failing test on master that was failing because github updated their docker and no longer supports `docker-compose`, only `docker compose`
- Adds `logs-dev` to `make deploy`
- Freezes new messages that come during the initial sync. Then process them all `MAX_MESSAGES_TO_PROCESS_AT_A_TIME` at a time after the initial sync is done.
Test plan
---
Already running in prod.

[#940] big queries fix

---

components/LandingPage/Navbar.tsx
pages/index.tsx

Related to #935 
Description
---
The button generator anchor link doesn't work if you navigate directly to /#button-generator. 
This change should fix it
Test plan
---
Preview the site and try loading http://localhost:3000/#button-generator
The page should scroll down to the button generator section

Bug: Fix button generator anchor link

---

components/Dashboard/Leaderboard.tsx
components/TableContainer/TableContainer.tsx

Related to #950 
Description
---
Fix Leaderboard Total revenue sorting, also fixed the behavior of sorting tables, before if we click twice the third click would remove sorting, now it will work just `asc` and `desc`, it wont remove the sorting in the third click
Test plan
---
Run server with `docker compose up` check Leaderboard total revenue table sorting.

fix: tables sorting

---

services/addressService.ts

Description
---
Removes `{include:  {transactions: true}}` from where is not needed.
Should save CPU from avoiding unnecessary huge JOIN clauses, if these addresses would have a lot of transactions.

chore: remove transactions include for other function

---

components/Admin/RegisteredUsers.tsx

Related to #968 
Description
---
Changed registered users table to use TableContainer component 
Test plan
---
run server with `docker compose up` check admin page Registered Users section

feat: registered users refactor

---

components/Auth/ForgotPassword.tsx
components/Auth/ResetPassword.tsx
components/Auth/SignIn.tsx
components/Auth/SignUp.tsx
components/Button/button.module.css
components/Button/index.tsx
components/Organization/CreateOrganization.tsx
components/Organization/DeleteOrganization.tsx
components/Organization/LeaveOrganization.tsx
components/Organization/UpdateOrganization.tsx
components/Organization/ViewOrganization.tsx
components/Organization/organization.module.css
components/Paybutton/EditButtonForm.tsx
components/Paybutton/PaybuttonForm.tsx
components/Paybutton/paybutton.module.css
components/Wallet/EditWalletForm.tsx
components/Wallet/WalletForm.tsx
pages/button/[id].tsx
pages/payments/index.tsx
styles/global.css
styles/variables.css

Related to #973
Description
---
The buttons throughout the app were pretty disjointed. They relied on a series of classnames, applied at each instance which was just pretty messy and causing some inconsistencies. 
Adding a reusable button component here to help with this.
It also handles the display of the loading state so that is more consistent, per #973
Note: I switched the order so the 'submit' buttons are on the right side of the create and edit forms. It seems more natural that way to me, but open leaving the order alone if you disagree  
Test plan
---
Preview the site and check the buttons in the app look and perform well

chore: Add button component 

---

components/Account/ChangePassword.tsx
components/Organization/UpdateOrganization.tsx
components/Paybutton/EditButtonForm.tsx
components/Paybutton/PaybuttonForm.tsx
components/Wallet/EditWalletForm.tsx
components/Wallet/WalletForm.tsx

Related to #542 
Description
---
Added a generic hook to autoFocus first input of forms in the dashboard
Test plan
---
- Go to buttons page, click in the button + to add a new button, check if the first field of the form is automatically focused  
- Also check other forms like wallets page forms to add a new wallet and to edit

feat: hook autofocus first input

---

ws-service/route.ts

Related to https://github.com/PayButton/paybutton/issues/474
Description
---
Improve the websocket server logs. 
Test plan
---
Make sure new connections are logged in the new format, prepended by the connection namespace, with the info of the socket id, client IP, timestamp and total clients connected to the namespace.

feat: better ws logs

---

pages/button/[id].tsx

Description
---
Fixes CORS issues in the button detail view by enforcing `websocket` as the connection, instead of `polling`.
Test plan
---
In master, acessing the button detail view should show CORS errors in the console, and therefore not allow for a real-time refresh of incoming txs. This PR should fix that.

fix: use websocket, not polling, on button detail view

---

ws-service/route.ts

Related to #
Description
---
Fixes issue where the websocket broadcast TX wouldn't appear for the client.
Test plan
---
Check if either a paybutton client hooked up to localhost OR localhost:3000/button/<uuid> are both  receiving living updates when a tx arrive.

fix: client not receiving broadcast tx

---

components/Auth/SignIn.tsx

Related to #990
Description
---
Fix the loading state of the submit button so it does not change state before changing pages when signing in
Test plan
---
Logout and then go to /sign-in. Signin and check the submit button behaves as expected. Try some incorrect credentials as well to test error behavior

[fix] Don't re-enable sign in button

---

services/triggerService.ts

Description
---
Fix logic for getting user from button trigger, that could lead to fetching the wrong user for a trigger.
Test plan
---
I couldn't reproduce getting another user's info in master, by having two users have buttons with the same address and different triggers, but it would still theoretically be possible.
In any case, triggers should still work normally.

fix: fetch user from trigger fix

---

components/ButtonGenerator/CodeBlock.tsx
components/ButtonGenerator/data.js
components/ButtonGenerator/index.tsx

Related to #
Added contributtionOffset and disableAltpayment props to paybutton generator.
Description
---
Test plan
---

feat: new props generator

---

PRIVACY.md
TERMS.md

Related to https://github.com/PayButton/wordpress-plugin/pull/60
Description
---
Introduces a simple privacy policy and terms of use. For now, we'll just limit it to `paybutton-server`.
Test plan
---
Think about what we're maybe missing, could use tweaking.

Added v1 Terms of Use & Privacy Policy.

---

pages/dashboard/index.tsx

Related to #936 
Description
---
Change dashboard Revenue and Payments indicators to show only the results from selected range of time.
Test plan
---
Check dashboard revenue and payments indicator

feat: show revenue selected time

---

package.json

Description
---
Stops the test command from simply opening the docker-exec-shortcuts.sh file instead of actually running the tests.
Test plan
---
Run `yarn docker test` and make sure it still works as expected in your environment.

Fix: 'yarn docker test' on Windows

---

README.md

Related to #952
Description
---
Added makefile commands to readme.
Test plan
---
Make sure each command works and that we didn't miss any.
Remarks
---
Note that since I'm on Windows, I can't test these make commands myself.

Chore: Added makefile commands to readme

---

components/Organization/UpdateOrganization.tsx
components/Organization/ViewOrganization.tsx
constants/index.ts
prisma/migrations/20250711220324_/migration.sql
prisma/schema.prisma
services/organizationService.ts
utils/validators.ts

Related to #1015 
Description
---
Added address to organization
Test plan
---
Open the dashboard, go to account, check address config

feat: org address

---

services/chronikService.ts
tests/unittests/chronikService.test.ts

Fixed potential Chronik service hashing bug with unexpected decodeCashAddress return type, added tests.
Related to #918.
Test plan
---
Run `yarn docker testcoverage` and make sure nothing related to addresses / hashing is broken.

New ChronikService tests

---

utils/validators.ts

Related to #1047 
Description
---
Ignore undefined fields when creating signature payload to remove the + sign in the beginning of the signature payload
Test plan
---
Create a POST trigger with txid, timestamp, and signature fields check if the signature payload fields does not have an extra + in the beginning

fix: ignore undefined fields signature
